// Generated by scripts/versioning.py from version.json. Do not edit.
package dev.chanho.hermes;

public final class BuildConfig {
    private BuildConfig() {}
    public static final int VERSION_CODE = 13;
    public static final String VERSION_NAME = "0.13";
    public static final String DISPLAY_VERSION = "v0.13";
    public static final String RELEASE_CHANNEL = "beta";
}
