package dev.chanho.hermes;
import android.content.Context;import android.util.AtomicFile;
import org.json.*;import java.nio.file.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.concurrent.atomic.AtomicInteger;
/** Production diagnostic capture/storage over real host files with explicit Android adapters. */
public final class DiagnosticsHarness {
 interface Work{void run()throws Exception;}static int passed;
 static void check(boolean v,String why){if(!v)throw new AssertionError(why);}static void test(String name,Work work)throws Exception{work.run();passed++;System.out.println("PASS "+name);}
 static Context context()throws Exception{return new Context(Files.createTempDirectory("hermes-diagnostics-").toFile());}
 static Path path(Context c){return c.getFilesDir().toPath().resolve("diagnostics/events.jsonl");}
 static Throwable error(int line){RuntimeException e=new RuntimeException("private-message API_KEY=fixture-private Authorization:Bearer fixture-private data:image/png;base64,private-pixels");e.setStackTrace(new StackTraceElement[]{new StackTraceElement("dev.chanho.hermes.Fixture","operation","Fixture.java",line)});return e;}
 public static void main(String[] ignored)throws Exception{
  test("durable diagnostic metadata excludes messages headers keys outputs and thoughts before and after reopen",()->{
   Context c=context();Throwable e=new RuntimeException("private-user-message"){public String getMessage(){throw new AssertionError("Diagnostics read raw exception message");}};e.setStackTrace(new StackTraceElement[]{new StackTraceElement("Fixture","operation","Fixture.java",7)});Diagnostics.record(c,"model_stream",e);
   JSONArray records=Diagnostics.snapshot(new Context(c.getFilesDir()));check(records.length()==1&&Files.size(path(c))>0,"diagnostic not durable");String saved=Files.readString(path(c));check(!saved.contains("private-")&&!saved.contains("message")&&!saved.contains("headers"),"private payload captured");
   Set<String> expected=new HashSet<>(Arrays.asList("schema","id","versionCode","versionName","phase","type","firstSeen","lastSeen","count","exceptions"));check(records.getJSONObject(0).keySet().equals(expected),"unbounded fields stored");
  });
  test("duplicate failures preserve firstSeen increment count and independent phases get separate IDs",()->{
   Context c=context();Diagnostics.record(c,"terminal",error(7));JSONObject first=Diagnostics.snapshot(c).getJSONObject(0);for(int i=0;i<5;i++)Diagnostics.record(c,"terminal",error(7));JSONArray same=Diagnostics.snapshot(c);check(same.length()==1&&same.getJSONObject(0).getLong("count")==6&&same.getJSONObject(0).getLong("firstSeen")==first.getLong("firstSeen"),"dedup damaged first appearance/count");Diagnostics.record(c,"storage",error(7));Diagnostics.record(c,"not-user-controlled-phase",error(7));JSONArray all=Diagnostics.snapshot(c);check(all.length()==3&&all.getJSONObject(2).getString("phase").equals("other"),"phase whitelist or fingerprint failed");
  });
  test("exception causes frames identifiers and file bytes remain bounded without raw content",()->{
   Context c=context();Throwable chain=null;StackTraceElement[] frames=new StackTraceElement[80];for(int i=0;i<frames.length;i++)frames[i]=new StackTraceElement("Class"+"x".repeat(140),"method"+"x".repeat(85),"File"+"x".repeat(80)+".java",i);
   for(int i=0;i<10;i++){RuntimeException e=new RuntimeException("private-thought-output",chain);e.setStackTrace(frames);chain=e;}Diagnostics.record(c,"runtime",chain);JSONArray causes=Diagnostics.snapshot(c).getJSONObject(0).getJSONArray("exceptions");check(causes.length()==4&&causes.getJSONObject(0).getJSONArray("frames").length()==12,"cause/frame bounds absent");check(!Files.readString(path(c)).contains("private-"),"raw cause message leaked");
   for(int i=0;i<50;i++){RuntimeException e=new RuntimeException("private",chain);e.setStackTrace(new StackTraceElement[]{new StackTraceElement("Fixture","operation","Fixture.java",i)});Diagnostics.record(c,"tool",e);}check(Files.size(path(c))<=262144,"diagnostic byte cap exceeded");check(Diagnostics.snapshot(c).getJSONObject(Diagnostics.snapshot(c).length()-1).getJSONArray("exceptions").getJSONObject(0).getJSONArray("frames").getJSONObject(0).getInt("line")==49,"latest failure not retained");
  });
  test("newest 256 failure records survive pruning and exact acknowledgements never clear unrelated errors",()->{
   Context c=context();for(int i=0;i<270;i++)Diagnostics.record(c,"tool",error(i));JSONArray all=Diagnostics.snapshot(c);check(all.length()==256,"record retention cap wrong");check(all.getJSONObject(0).getJSONArray("exceptions").getJSONObject(0).getJSONArray("frames").getJSONObject(0).getInt("line")==14,"pruning lost newest preference");String acknowledged=all.getJSONObject(0).getString("id"),last=all.getJSONObject(255).getString("id");Diagnostics.acknowledge(c,new JSONArray().put(acknowledged).put("invalid-id").put("f".repeat(64)));JSONArray remain=Diagnostics.snapshot(c);check(remain.length()==255&&!remain.toString().contains(acknowledged)&&remain.toString().contains(last),"acknowledgement removed unrelated failure");
  });
  test("reloading sanitizes extra private fields malformed lines and credential-shaped source identifiers",()->{
   Context c=context();Diagnostics.record(c,"ui",error(7));JSONObject raw=Diagnostics.snapshot(c).getJSONObject(0);raw.put("message","private-user-message").put("headers","private-api-key").put("thought","private-provider-output");JSONObject frame=raw.getJSONArray("exceptions").getJSONObject(0).getJSONArray("frames").getJSONObject(0);frame.put("class","sk-fixture_private_123").put("method","ghp_private_token_123").put("source","Authorization:Bearer private").put("output","private-shell-output");Files.writeString(path(c),raw+"\nnot-json\n");String safe=Diagnostics.snapshot(c).toString();check(!safe.contains("private")&&safe.contains("unknown"),"reloaded diagnostic bypassed metadata privacy");
  });
  test("failed host atomic adapter commit restores previous bytes and concurrent recording deduplicates without corrupting file",()->{
   Context c=context();Diagnostics.record(c,"bridge",error(7));byte[] before=Files.readAllBytes(path(c));AtomicFile.failFinish=true;try{Diagnostics.record(c,"bridge",error(8));}finally{AtomicFile.failFinish=false;}check(Arrays.equals(before,Files.readAllBytes(path(c))),"failed commit damaged old diagnostics");List<Thread> workers=new ArrayList<>();for(int i=0;i<20;i++){Thread t=new Thread(()->Diagnostics.record(c,"bridge",error(7)));workers.add(t);t.start();}for(Thread t:workers)t.join();JSONArray records=Diagnostics.snapshot(c);check(records.length()==1&&records.getJSONObject(0).getLong("count")==21,"parallel record corrupted dedup/count");
  });
  test("browser diagnostics preserve only bounded known source locations and never arbitrary JavaScript message or stack",()->{
   Context c=context();Diagnostics.recordBrowserProblem(c,"webview_error","file:///private/token",-1,Integer.MAX_VALUE);Diagnostics.recordBrowserProblem(c,"webview_error","file:///private/token",-1,Integer.MAX_VALUE);Diagnostics.recordBrowserProblem(c,"unhandled_rejection","app.js",77,2);Diagnostics.recordBrowserProblem(c,"script_error","index.html",1,2);JSONArray rows=Diagnostics.snapshot(c);check(rows.length()==2&&rows.getJSONObject(0).getLong("count")==2,"browser code gate or dedup failed");JSONObject event=rows.getJSONObject(0);check(event.getString("type").equals("browser_error")&&event.getString("source").equals("unknown")&&event.getInt("line")==0&&event.getInt("column")==10000000&&!event.has("exceptions"),"browser source/location not bounded");check(!Files.readString(path(c)).contains("private"),"browser raw URL retained");
  });
  test("own process crash and ANR history excludes normal exits descriptions and traces and does not invent historical version",()->{
   Context c=context();for(int reason:new int[]{1,4,5,6,10})c.activityManager.exits.add(new android.app.ApplicationExitInfo(reason,1000+reason,100+reason));Diagnostics.collectPreviousProcessExits(c);JSONArray exits=Diagnostics.snapshot(c);check(exits.length()==3,"normal exits classified as crash or genuine crashes omitted");check(c.activityManager.requestedPackage.equals("dev.chanho.hermes")&&c.activityManager.requestedPid==0&&c.activityManager.requestedLimit==5,"OS history query not limited to own app");for(int i=0;i<exits.length();i++){JSONObject e=exits.getJSONObject(i);check(e.getString("type").equals("process_exit")&&e.getString("versionMeaning").equals("observed_at_startup")&&!e.has("exceptions")&&!e.has("description")&&!e.has("trace"),"OS crash provenance/private traces fabricated");}Diagnostics.collectPreviousProcessExits(c);check(Diagnostics.snapshot(c).length()==3&&Diagnostics.snapshot(c).getJSONObject(0).getLong("count")==1,"same historical exit counted repeatedly");android.os.Build.VERSION.SDK_INT=29;try{Context older=context();older.activityManager.exits.add(new android.app.ApplicationExitInfo(4,100,7));Diagnostics.collectPreviousProcessExits(older);check(Diagnostics.snapshot(older).length()==0&&older.activityManager.requestedPackage==null,"unsupported API invoked OS history");}finally{android.os.Build.VERSION.SDK_INT=35;}
  });
  test("strict release export refuses corrupt metadata instead of reporting missing errors as clean",()->{
   Context c=context();Diagnostics.record(c,"runtime",error(7));check(Diagnostics.snapshotForExport(c).length()==1,"valid metadata export failed");JSONObject valid=Diagnostics.snapshot(c).getJSONObject(0);for(Object schema:new Object[]{2,"1",JSONObject.NULL}){JSONObject invalid=new JSONObject(valid.toString());invalid.put("schema",schema);Files.writeString(path(c),invalid.toString()+"\n",StandardCharsets.UTF_8);check(Diagnostics.snapshot(c).length()==0,"invalid schema accepted by reload");try{Diagnostics.snapshotForExport(c);throw new AssertionError("invalid schema exported as clean");}catch(java.io.IOException expected){}}Files.writeString(path(c),valid.toString().replace("\"schema\":1","\"schema\":1.0")+"\n",StandardCharsets.UTF_8);try{Diagnostics.snapshotForExport(c);throw new AssertionError("floating schema falsely exported clean");}catch(java.io.IOException expected){}JSONObject missing=new JSONObject(valid.toString());missing.remove("schema");Files.writeString(path(c),missing.toString()+"\n",StandardCharsets.UTF_8);try{Diagnostics.snapshotForExport(c);throw new AssertionError("missing schema falsely exported clean");}catch(java.io.IOException expected){}Files.writeString(path(c),valid.toString()+"\n",StandardCharsets.UTF_8);Files.writeString(path(c),"corrupt not-json\n",StandardCharsets.UTF_8,StandardOpenOption.APPEND);check(Diagnostics.snapshot(c).length()==1,"best-effort snapshot lost valid prior record");try{Diagnostics.snapshotForExport(c);throw new AssertionError("corrupt metadata falsely exported clean");}catch(java.io.IOException expected){}
  });
  test("uncaught capture records before delegating unchanged original Throwable and does not replace previous crash authority",()->{
   Context c=context();Thread.UncaughtExceptionHandler original=Thread.getDefaultUncaughtExceptionHandler();AtomicInteger delegated=new AtomicInteger();Throwable e=error(27);Thread current=Thread.currentThread();Thread.setDefaultUncaughtExceptionHandler((thread,error)->{check(thread==current&&error==e,"crash delegate arguments changed");check(Diagnostics.snapshot(c).length()==1,"delegate ran before durable crash record");delegated.incrementAndGet();});
   try{Diagnostics.initialize(c);Thread.UncaughtExceptionHandler installed=Thread.getDefaultUncaughtExceptionHandler();Diagnostics.initialize(context());check(Thread.getDefaultUncaughtExceptionHandler()==installed,"initialize replaced installed handler");installed.uncaughtException(current,e);check(delegated.get()==1&&Diagnostics.snapshot(c).getJSONObject(0).getString("type").equals("uncaught"),"previous handler or uncaught type lost");}finally{Thread.setDefaultUncaughtExceptionHandler(original);}
  });
  System.out.println("Diagnostics: "+passed+" production capture/host-filesystem checks; Android AtomicFile and process crash behavior are separate proof.");
 }
}
