package dev.chanho.hermes;
import org.json.*;
import com.sun.net.httpserver.*;
import java.util.*;
import java.io.*;
import java.nio.charset.StandardCharsets;

/** Real loopback model requests, never live credentials or providers. */
public final class ContextCompactorHarness {
 static int passed;
 static void check(boolean b,String m){if(!b)throw new AssertionError(m);}
 interface Work{void run()throws Exception;}
 static void test(String n,Work w)throws Exception{w.run();passed++;System.out.println("PASS "+n);}
 static String repeat(String value,int count){StringBuilder s=new StringBuilder();for(int i=0;i<count;i++)s.append(value);return s.toString();}
 static JSONArray history()throws Exception{return J.arr(J.obj("role","system","content","system"),J.obj("role","user","content","My name is Ada, don't retry denied payments. file=/workspace/a.md"),J.obj("role","assistant","content",JSONObject.NULL,"reasoning_content","private-provider-replay","tool_calls",J.arr(J.obj("id","c1","type","function","function",J.obj("name","terminal","arguments","{}")))),J.obj("role","tool","tool_call_id","c1","content",repeat("actual result denied no execution ",200)),J.obj("role","assistant","content","Observed denial"),J.obj("role","user","content","Continue latest task"));}
 static String summary="## Goal\nContinue task\n## User facts and preferences\nAda; no denied payment retry\n## Completed actions and actual tool results\nDenied, not executed\n## Current task and pending actions\nContinue latest task\n## Files, skills, identifiers and recovery pointers\n/workspace/a.md\n## Constraints and unresolved errors\nNo permission expansion";
 static String sse(String text){return "data: "+J.obj("choices",J.arr(J.obj("delta",J.obj("content",text),"finish_reason",JSONObject.NULL)))+"\n\ndata: "+J.obj("choices",J.arr(J.obj("delta",new JSONObject(),"finish_reason","stop")))+"\n\ndata: [DONE]\n\n";}
 public static void main(String[] args)throws Exception{
  test("official MiMo and API metadata budgets exceed old char cap without inventing unknown limits",()->{ModelLimits m=ModelLimits.resolve(J.obj("providerId","xiaomi","model","mimo-v2.6-flash"));check(m.verified&&m.context==1000000&&m.output==128000,"official limit wrong");ModelLimits u=ModelLimits.resolve(J.obj("model","unknown"));check(!u.verified,"unknown maximum falsely guaranteed");JSONObject api=LocalCapabilities.normalizeModels(J.obj("data",J.arr(J.obj("id","fixture","context_length",262144,"top_provider",J.obj("max_completion_tokens",32000))))).getJSONArray("models").getJSONObject(0);check(api.getLong("contextTokens")==262144&&api.getLong("outputTokens")==32000,"API metadata lost");});
  test("pair-aligned checkpoint preserves facts, current user, original history, and full reasoning replay in retained tail",()->{JSONArray h=history();String original=h.toString();List<JSONArray> summarized=new ArrayList<>();ContextCompactor.State s=ContextCompactor.compact(h,new ContextCompactor.State(),8000,(msgs,prior)->{summarized.add(msgs);return summary;});JSONArray wire=ContextCompactor.project(h,s,"session");check(h.toString().equals(original),"full transcript rewritten");check(wire.toString().contains("Ada")&&wire.toString().contains("Continue latest task")&&wire.toString().contains("session_search"),"facts/task/recovery lost");check(!summarized.toString().contains("private-provider-replay"),"hidden replay leaked to summarizer");for(int i=1;i<wire.length();i++)if("tool".equals(wire.getJSONObject(i).optString("role")))check("assistant".equals(wire.getJSONObject(i-1).optString("role")),"tool orphaned");ContextCompactor.State loaded=ContextCompactor.load(ContextCompactor.encode(s),h);check(loaded.covered==s.covered,"checkpoint reload lost");h.getJSONObject(1).put("content","changed");check(ContextCompactor.load(ContextCompactor.encode(s),h).covered==1,"stale fingerprint accepted");});
  test("oversized completed tool batch is summarized in ordered bounded parts with every original byte retained",()->{
   JSONArray h=history();h.remove(h.length()-1);h.remove(h.length()-1);String large=repeat("한😀actual-output ",2500);h.getJSONObject(3).put("content",large);String original=h.toString();java.util.List<JSONObject> fragments=new java.util.ArrayList<>();ContextCompactor.State compact=ContextCompactor.compact(h,new ContextCompactor.State(),12000,(rows,prior)->{for(int i=0;i<rows.length();i++){JSONObject row=rows.getJSONObject(i);if("tool".equals(row.optString("record_role")))fragments.add(row);}return summary;});check(compact.covered==h.length(),"oversized completed batch not compacted whole");StringBuilder recovered=new StringBuilder();for(JSONObject part:fragments)recovered.append(part.getString("record_json_fragment"));check(new JSONObject(recovered.toString()).getString("content").equals(large),"tool output fragment bytes omitted or unicode corrupted");JSONArray wire=ContextCompactor.project(h,compact,"s");check(wire.length()==3&&wire.getJSONObject(2).getString("role").equals("user"),"current user not verbatim or orphaned tool retained");check(h.toString().equals(original),"full original changed");
  });
  test("incomplete summary does not commit or mutate original",()->{JSONArray h=history();String original=h.toString();boolean rejected=false;try{ContextCompactor.compact(h,new ContextCompactor.State(),8000,(a,b)->"partial");}catch(IllegalStateException e){rejected=true;}check(rejected&&original.equals(h.toString()),"partial summary accepted or history lost");});
  test("typed overflow differs from quota authentication and opaque errors; error text stays private",()->{Net.ApiError overflow=Net.apiError(400,J.obj("error",J.obj("code","context_length_exceeded","message","maximum context length is 16,384 tokens; private secret")).toString());check(overflow.contextOverflow&&overflow.contextLimit==16384&&!overflow.getMessage().contains("secret"),"typed overflow missing or private text exposed");check(!Net.apiError(429,J.obj("error",J.obj("message","token limit exceeded")).toString()).contextOverflow,"rate quota retried");check(!Net.apiError(401,J.obj("error",J.obj("code","context_length_exceeded")).toString()).contextOverflow,"auth retried");check(!Net.apiError(400,"raw context_length_exceeded").contextOverflow,"untyped text retried");});
  test("real HTTP overflow summarizes once resubmits model and retains all local messages without executing a tool",()->{
   HttpServer server=HttpServer.create(new java.net.InetSocketAddress("127.0.0.1",0),0);List<JSONObject> requests=Collections.synchronizedList(new ArrayList<>());server.createContext("/v1/chat/completions",exchange->{try{JSONObject req=new JSONObject(new String(exchange.getRequestBody().readAllBytes(),StandardCharsets.UTF_8));requests.add(req);boolean compact=req.getJSONArray("messages").getJSONObject(0).optString("content").equals(ContextCompactor.PROMPT);int code=requests.size()==1?400:200;String payload=code==400?J.obj("error",J.obj("code","context_length_exceeded","message","maximum context length is 16384 tokens")).toString():sse(compact?summary:"Final correct answer");exchange.getResponseHeaders().set("Content-Type",code==400?"application/json":"text/event-stream");byte[] b=payload.getBytes(StandardCharsets.UTF_8);exchange.sendResponseHeaders(code,b.length);exchange.getResponseBody().write(b);exchange.close();}catch(Exception e){throw new RuntimeException(e);}});server.start();try{AgentRuntime r=new AgentRuntime();JSONArray h=history();r.store.transcript("overflow",h);JSONObject config=J.obj("endpoint","http://127.0.0.1:"+server.getAddress().getPort()+"/v1","model","fixture","enabledPlugins",J.arr("device"),"maxRounds",2);String finalAnswer=new DirectAgent(r).run("overflow","Newest request",config,"fixture-only");check(finalAnswer.equals("Final correct answer"),"no final answer");check(requests.size()==3,"not exactly rejection + summary + resubmit");check(requests.get(2).getJSONArray("messages").toString().contains("CONTEXT CHECKPOINT"),"resubmit not compacted");check(r.store.transcript("overflow").length()==8&&r.store.transcript("overflow").toString().contains("private-provider-replay"),"full local history removed");}finally{server.stop(0);}
  });
  System.out.println("ContextCompactor: "+passed+" checks; HTTP fixtures only, no live provider claim.");
 }
}
