"""Mobile preferences UI using a native bridge double, never a real provider."""
import sys, unittest
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))
import test_ui as ui_helpers

class PreferencesUITest(unittest.TestCase):
    setUpClass=classmethod(ui_helpers.UITest.setUpClass.__func__)
    tearDownClass=classmethod(ui_helpers.UITest.tearDownClass.__func__)
    setUp=ui_helpers.UITest.setUp
    tearDown=ui_helpers.UITest.tearDown
    navigate=ui_helpers.UITest.navigate
    open_provider_details=ui_helpers.UITest.open_provider_details
    def setup_bridge(self, config=None):
        self.page.evaluate("""override => {
          window.testPackets=[];
          window.testConfig={mode:'direct',endpoint:'https://saved.example/v1',model:'model-0',reasoningEffort:'auto',skillId:'general',enabledPlugins:['device','screen','root'],allowedApps:[],...override};
          NativeBridge={postMessage(raw){
            const p=JSON.parse(raw);testPackets.push(p);let data={};
            if(p.method==='boot')data={config:testConfig,sessions:[],audit:[],device:{},version:'0.02'};
            if(p.method==='listModels')data={models:Array.from({length:12},(_,i)=>({id:'model-'+i,name:i===10?'<script>literal</script>':'Model '+i,reasoningSupported:false,reasoningSupportSource:'unknown'}))};
            if(p.method==='setCapabilities'){testConfig={...testConfig,...p.data};data=testConfig;}
            if(['messages','sessions','audit'].includes(p.method))data=[];
            setTimeout(()=>PocketNative({id:p.id,ok:true,data}),0);
          }};boot();
        }""", config or {})
        expected={'model':'model-0',**(config or {})}
        self.page.wait_for_function('expected => Object.entries(expected).every(([key,value]) => JSON.stringify(state.config[key]) === JSON.stringify(value))',arg=expected)

    def test_popup_focus_escape_native_back_and_background_inert(self):
        self.setup_bridge()
        self.page.locator('#composerTools').click()
        self.assertTrue(self.page.locator('#capabilitySheet').is_visible())
        self.assertEqual(self.page.evaluate('document.activeElement.id'),'closeCapabilities')
        self.assertTrue(self.page.locator('#main').evaluate('(e)=>e.inert'))
        self.page.keyboard.press('Escape')
        self.assertFalse(self.page.locator('#capabilitySheet').is_visible())
        self.assertEqual(self.page.evaluate('document.activeElement.id'),'composerTools')
        self.page.locator('#composerTools').click()
        self.page.evaluate('PocketBack()')
        self.assertFalse(self.page.locator('#capabilitySheet').is_visible())
        self.assertFalse(self.page.locator('#main').evaluate('(e)=>e.inert'))
        self.page.locator('#composerTools').click()
        self.page.locator('#capabilitySheet .sheet-scrim').click(position={'x':20,'y':20})
        self.assertFalse(self.page.locator('#capabilitySheet').is_visible())
        self.assertEqual(self.errors,[])

    def test_skill_plugin_partial_save_preserves_unsaved_api_secret(self):
        self.setup_bridge();self.navigate('settings')
        self.page.locator('#settingsConnection').click()
        self.open_provider_details()
        self.page.locator('#manualModelDetails').evaluate('(e)=>e.open=true')
        self.page.locator('#endpoint').fill('https://draft.example/v1')
        self.page.locator('#token').fill('draft-test-secret')
        self.page.locator('#model').fill('draft-model')
        self.navigate('chat');self.page.locator('#composerTools').click()
        self.page.locator('input[name=skills][value=code]').check()
        self.page.locator('[data-capability-tab=plugins]').click()
        self.page.locator('input[name=plugins][value=root]').uncheck()
        self.page.locator('#capabilityApply').click()
        self.page.wait_for_function('() => state.config.skillId === "code"')
        packet=self.page.evaluate("testPackets.find(p=>p.method==='setCapabilities').data")
        self.assertEqual(packet,{'skillId':'code','enabledPlugins':['device','screen'],'activeSkillName':''})
        self.assertEqual(self.page.locator('#token').input_value(),'draft-test-secret')
        self.assertEqual(self.page.locator('#endpoint').input_value(),'https://draft.example/v1')
        self.assertEqual(self.page.locator('#model').input_value(),'draft-model')
        self.assertEqual(self.page.evaluate('state.config.endpoint'),'https://saved.example/v1')
        self.assertFalse(self.page.locator('#capabilitySheet').is_visible())
        self.assertEqual(self.errors,[])

    def test_catalog_five_rows_and_independent_model_thinking_preferences(self):
        self.setup_bridge({'reasoningEffort':'medium'});self.page.locator('#composerConnection').click()
        self.page.wait_for_function('() => document.querySelectorAll(".model-option").length===12')
        self.assertFalse(self.page.locator('#reasoningSheet').is_visible())
        self.assertEqual(self.page.locator('#modelSheet [data-reasoning-effort]').count(),0)
        bounds=self.page.locator('#modelResults').evaluate('e=>({height:e.clientHeight,scroll:e.scrollHeight,row:e.querySelector("button").getBoundingClientRect().height,overflow:getComputedStyle(e).overflowY})')
        self.assertGreater(bounds['scroll'],bounds['height'])
        self.assertLessEqual(bounds['height'],bounds['row']*5+2)
        self.assertIn(bounds['overflow'],('auto','scroll'))
        later=self.page.locator('.model-option').filter(has_text='Model 9')
        later.scroll_into_view_if_needed();later.click()
        self.page.wait_for_function('() => state.config.model === "model-9"')
        self.assertEqual(self.page.evaluate("testPackets.find(p=>p.method==='setCapabilities').data"),{'model':'model-9'})
        self.assertEqual(self.page.evaluate('state.config.reasoningEffort'),'medium')
        self.assertFalse(self.page.locator('#modelSheet').is_visible())
        requests=self.page.evaluate("testPackets.filter(p=>p.method==='listModels').length")
        self.page.locator('#reasoningPicker').click()
        self.assertTrue(self.page.locator('#reasoningSheet').is_visible())
        self.assertFalse(self.page.locator('#modelSheet').is_visible())
        self.assertEqual(self.page.locator('#reasoningSheet .model-option').count(),0)
        self.page.locator('[data-reasoning-effort="high"]').click()
        self.page.wait_for_function('() => state.config.reasoningEffort === "high"')
        self.assertEqual(self.page.evaluate("testPackets.filter(p=>p.method==='setCapabilities').at(-1).data"),{'reasoningEffort':'high'})
        self.assertEqual(self.page.evaluate('state.config.model'),'model-9')
        self.assertEqual(self.page.evaluate("testPackets.filter(p=>p.method==='listModels').length"),requests)
        self.assertIn('높음',self.page.locator('#composerThinking').inner_text())
        self.assertEqual(self.errors,[])

    def test_model_search_literal_name_and_manual_fallback(self):
        self.setup_bridge();self.page.locator('#composerConnection').click()
        self.page.wait_for_function('() => document.querySelectorAll(".model-option").length===12')
        self.assertEqual(self.page.locator('#modelResults script').count(),0)
        self.page.locator('#modelSearch').fill('literal')
        self.assertEqual(self.page.locator('.model-option').count(),1)
        self.page.locator('#modelSearch').fill('nothing-matches')
        self.assertEqual(self.page.locator('.model-option').count(),0)
        self.page.locator('#sheetApiSettings').click()
        self.page.locator('#manualModelDetails').evaluate('(e)=>e.open=true')
        self.page.locator('#model').fill('manual-provider-id')
        self.page.locator('#saveDefaults').click()
        self.page.wait_for_function('() => state.config.model === "manual-provider-id"')
        self.assertEqual(self.page.evaluate('state.config.reasoningEffort'),'auto')
        self.assertEqual(self.errors,[])

    def test_provider_first_catalog_switch_resets_draft_secret_and_selects_model_after_save(self):
        self.setup_bridge()
        self.page.evaluate("""() => {
          const base=NativeBridge.postMessage;
          NativeBridge.postMessage=raw=>{const p=JSON.parse(raw);if(p.method!=='saveSettings')return base(raw);testPackets.push(p);testConfig={...testConfig,...p.data,hasToken:!!p.data.token};delete testConfig.token;setTimeout(()=>PocketNative({id:p.id,ok:true,data:testConfig}),0);};
        }""")
        self.navigate('settings')
        self.page.locator('#settingsConnection').click()
        self.open_provider_details()
        self.assertEqual(self.page.locator('#providerSelect').input_value(),'custom')
        self.assertEqual(self.page.locator('#endpoint').input_value(),'https://saved.example/v1')
        self.page.locator('#token').fill('previous-draft-secret')
        self.page.locator('#providerSelect').select_option('openai-api')
        self.assertEqual(self.page.locator('#token').input_value(),'')
        self.assertEqual(self.page.locator('#model').input_value(),'')
        self.assertEqual(self.page.locator('#reasoningEffort').input_value(),'auto')
        self.assertEqual(self.page.locator('#endpoint').input_value(),'https://api.openai.com/v1')
        self.assertTrue(self.page.locator('#endpoint').evaluate('(e)=>e.readOnly'))
        self.assertFalse(self.page.locator('#endpointDetails').is_visible())
        self.assertFalse(self.page.locator('#settingsModelSection').is_visible())
        self.page.locator('#token').fill('new-provider-test-secret')
        self.page.locator('#saveConnection').click()
        self.page.wait_for_function("() => testPackets.some(p=>p.method==='saveSettings')")
        packet=self.page.evaluate("testPackets.find(p=>p.method==='saveSettings').data")
        self.assertEqual(packet['providerId'],'openai-api')
        self.assertEqual(packet['endpoint'],'https://api.openai.com/v1')
        self.assertEqual(packet['token'],'new-provider-test-secret')
        self.assertEqual(packet['model'],'')
        self.assertEqual(packet['reasoningEffort'],'auto')
        self.page.wait_for_function('() => document.querySelectorAll(".model-option").length===12')
        self.assertTrue(self.page.locator('#modelSheet').is_visible())
        self.page.locator('.model-option').filter(has_text='Model 3').click()
        self.page.wait_for_function('() => state.config.model === "model-3"')
        self.navigate('chat')
        self.page.locator('#reasoningPicker').click()
        self.page.locator('[data-reasoning-effort="medium"]').click()
        self.page.wait_for_function('() => state.config.reasoningEffort === "medium"')
        self.assertEqual(self.page.evaluate('state.config.reasoningEffort'),'medium')
        self.assertEqual(self.page.locator('#token').input_value(),'')
        self.assertEqual(self.errors,[])

    def test_native_provider_catalog_drives_names_and_builtin_endpoint(self):
        self.setup_bridge()
        self.page.evaluate("""() => {
          state.capabilities={...capabilityFallback,providers:[{id:'openrouter',name:'Native catalog router',endpoint:'https://openrouter.ai/api/v1',requiresKey:true,description:'native description'},{id:'custom',name:'Native custom',endpoint:'',requiresKey:false}]};initProviders();
        }""")
        self.navigate('settings')
        self.page.locator('#settingsConnection').click()
        self.open_provider_details()
        self.assertEqual(self.page.locator('#providerSelect option').count(),3)
        self.assertIn('Native catalog router',self.page.locator('#providerSelect').inner_text())
        self.page.locator('#providerSelect').select_option('openrouter')
        self.assertEqual(self.page.locator('#endpoint').input_value(),'https://openrouter.ai/api/v1')
        self.assertEqual(self.page.locator('#providerDescription').inner_text(),'native description')
        self.assertTrue(self.page.locator('#token').evaluate('(e)=>e.required'))
        self.page.locator('#providerSelect').select_option('custom')
        self.open_provider_details()
        self.assertFalse(self.page.locator('#endpoint').evaluate('(e)=>e.readOnly'))
        self.assertTrue(self.page.locator('#endpointDetails').is_visible())
        self.assertFalse(self.page.locator('#token').evaluate('(e)=>e.required'))
        self.assertEqual(self.errors,[])

    def test_default_model_and_hermes_reasoning_ladder_persist_new_chat_and_boot(self):
        self.setup_bridge();self.page.locator('#composerConnection').click()
        self.page.wait_for_function('() => document.querySelectorAll(".model-option").length===12')
        self.page.locator('.model-option').filter(has_text='Model 4').click()
        self.page.wait_for_function('() => state.config.model === "model-4"')
        self.page.locator('#reasoningPicker').click()
        values=self.page.locator('#sheetReasoning option').evaluate_all('(options)=>options.map(o=>o.value)')
        for effort in ('auto','none','minimal','low','medium','high','xhigh','max','ultra'):
            self.assertIn(effort,values)
        self.page.locator('[data-reasoning-effort="xhigh"]').click()
        self.page.wait_for_function('() => state.config.reasoningEffort === "xhigh"')
        self.page.locator('#headerNewChat').click()
        self.assertEqual(self.page.evaluate('state.config.model'),'model-4')
        self.assertEqual(self.page.evaluate('state.config.reasoningEffort'),'xhigh')
        self.page.evaluate('boot()')
        self.page.wait_for_function('() => document.getElementById("reasoningEffort").value === "xhigh"')
        self.page.locator('#reasoningPicker').click()
        self.assertFalse(self.page.locator('#modelSheet').is_visible())
        self.assertEqual(self.page.locator('#sheetReasoning').input_value(),'xhigh')
        self.assertIn('매우 높음',self.page.locator('#composerThinking').inner_text())
        self.assertEqual(self.errors,[])

    def test_settings_home_keeps_connection_draft_and_removes_manual_context_controls(self):
        self.setup_bridge();self.navigate('settings')
        self.assertTrue(self.page.locator('#settingsHome').is_visible())
        self.page.locator('#settingsConnection').click();self.open_provider_details()
        self.page.locator('#token').fill('unsaved-provider-secret')
        self.assertTrue(self.page.locator('#allowLan').is_visible())
        self.assertEqual(self.page.locator('#settingsAdvanced,#maxRounds,#contextChars,#saveAdvanced').count(),0)
        self.page.evaluate('PocketBack()')
        self.assertTrue(self.page.locator('#settingsHome').is_visible())
        self.assertEqual(self.page.locator('#token').input_value(),'unsaved-provider-secret')
        self.assertEqual(self.page.evaluate('state.config.endpoint'),'https://saved.example/v1')
        self.assertEqual(self.page.evaluate("testPackets.filter(p=>p.method==='setCapabilities'||p.method==='saveSettings').length"),0)
        self.page.locator('#settingsAppearance').click()
        self.assertEqual(self.page.locator('[data-design-choice]').count(),2)
        self.assertEqual(self.errors,[])

    def test_short_drawer_last_button_is_reachable_and_does_not_clip(self):
        self.page.set_viewport_size({'width':393,'height':420})
        self.page.locator('#menuToggle').click()
        last=self.page.locator('#sidebar [data-page="settings"]');last.scroll_into_view_if_needed()
        bounds=last.bounding_box();self.assertGreaterEqual(bounds['y'],0)
        self.assertLessEqual(bounds['y']+bounds['height'],422)
        last.click();self.assertTrue(self.page.locator('#page-settings').is_visible())
        self.assertEqual(self.errors,[])

    def test_failed_model_discovery_does_not_fake_models_or_prevent_manual_id(self):
        self.setup_bridge()
        self.page.evaluate("""() => {const base=NativeBridge.postMessage;NativeBridge.postMessage=raw=>{const p=JSON.parse(raw);if(p.method!=='listModels')return base(raw);testPackets.push(p);setTimeout(()=>PocketNative({id:p.id,ok:false,data:{message:'fixture API unauthorized'}}),0);};}""")
        self.page.locator('#composerConnection').click()
        self.page.wait_for_function("() => document.getElementById('modelStatus').textContent.includes('fixture API unauthorized')")
        self.assertEqual(self.page.locator('.model-option').count(),0)
        self.assertIn('직접 입력',self.page.locator('#modelStatus').inner_text())
        self.page.locator('#sheetApiSettings').click()
        self.page.locator('#manualModelDetails').evaluate('(e)=>e.open=true')
        self.page.locator('#model').fill('known-id')
        self.page.locator('#saveDefaults').click()
        self.page.wait_for_function('() => state.config.model === "known-id"')
        self.assertEqual(self.errors,[])

    def test_first_launch_setup_guide_disables_shortcuts_and_does_not_call_api(self):
        self.setup_bridge({'model':'','endpoint':'','providerId':'openrouter','hasToken':False})
        self.assertTrue(self.page.locator('#setupDialog').is_visible())
        panel=self.page.locator('#setupDialog .sheet-panel').bounding_box()
        self.assertAlmostEqual(panel['y']+panel['height']/2,self.page.viewport_size['height']/2,delta=20)
        self.assertTrue(self.page.locator('#composerConnection').is_disabled())
        self.assertTrue(self.page.locator('#reasoningPicker').is_disabled())
        self.assertEqual(self.page.evaluate("testPackets.filter(p=>['listModels','testConnection','startChat'].includes(p.method)).length"),0)
        self.page.locator('#setupGoSettings').click()
        self.assertTrue(self.page.locator('#settingsPanelConnection').is_visible())
        self.assertFalse(self.page.locator('#setupDialog').is_visible())
        self.assertEqual(self.page.evaluate("testPackets.filter(p=>['listModels','testConnection','startChat'].includes(p.method)).length"),0)
        self.assertEqual(self.errors,[])

    def test_hosted_model_without_saved_key_stays_disabled_until_key_exists(self):
        hosted={'providerId':'openai-api','endpoint':'https://api.openai.com/v1','model':'saved-model','hasToken':False}
        self.setup_bridge(hosted)
        self.assertTrue(self.page.locator('#setupDialog').is_visible())
        panel=self.page.locator('#setupDialog .sheet-panel').bounding_box()
        self.assertAlmostEqual(panel['y']+panel['height']/2,self.page.viewport_size['height']/2,delta=20)
        self.assertTrue(self.page.locator('#composerConnection').is_disabled())
        self.assertTrue(self.page.locator('#reasoningPicker').is_disabled())
        self.page.locator('#setupLater').click()
        self.page.locator('#messageInput').fill('Waiting for API setup')
        self.assertTrue(self.page.locator('#sendMessage').is_disabled())
        self.assertEqual(self.page.evaluate("testPackets.filter(p=>['listModels','testConnection','startChat'].includes(p.method)).length"),0)
        self.setup_bridge({**hosted,'hasToken':True})
        self.assertFalse(self.page.locator('#composerConnection').is_disabled())
        self.assertFalse(self.page.locator('#reasoningPicker').is_disabled())
        self.assertFalse(self.page.locator('#sendMessage').is_disabled())
        self.assertEqual(self.errors,[])

    def test_thinking_popup_focus_and_cancel_preserves_model_and_default(self):
        self.setup_bridge({'reasoningEffort':'medium'})
        self.page.locator('#reasoningPicker').click()
        self.assertEqual(self.page.evaluate('document.activeElement.id'),'closeReasoning')
        self.assertTrue(self.page.locator('#main').evaluate('(e)=>e.inert'))
        self.assertEqual(self.page.locator('#reasoningSheet [data-reasoning-effort]').count(),9)
        self.page.keyboard.press('Escape')
        self.assertEqual(self.page.evaluate('document.activeElement.id'),'reasoningPicker')
        self.assertFalse(self.page.locator('#reasoningSheet').is_visible())
        self.assertEqual(self.page.evaluate('state.config.model'),'model-0')
        self.assertEqual(self.page.evaluate('state.config.reasoningEffort'),'medium')
        self.assertEqual(self.page.evaluate("testPackets.filter(p=>p.method==='listModels'||p.method==='setCapabilities').length"),0)
        self.assertEqual(self.errors,[])

    def test_configured_header_is_plain_and_current_chat_has_no_sidebar_nav(self):
        self.setup_bridge()
        self.assertFalse(self.page.locator('#setupDialog').is_visible())
        self.assertFalse(self.page.locator('#composerConnection').is_disabled())
        self.assertFalse(self.page.locator('#reasoningPicker').is_disabled())
        self.assertNotEqual(self.page.locator('#brand').evaluate('(e)=>e.tagName'),'BUTTON')
        self.assertEqual(self.page.locator('#brand button,#activeModel,#activeReasoning').count(),0)
        self.page.locator('#brand').click()
        self.assertFalse(self.page.locator('#modelSheet').is_visible())
        self.assertFalse(self.page.locator('#reasoningSheet').is_visible())
        self.assertEqual(self.page.locator('#sidebar [data-page="chat"]').count(),0)
        self.assertEqual(self.errors,[])

    def test_capability_draft_requires_save_and_close_does_not_change_saved_plugins(self):
        self.setup_bridge();self.page.locator('#composerTools').click()
        self.assertTrue(self.page.locator('#capabilityApply').is_disabled())
        self.page.locator('[data-capability-tab=plugins]').click()
        self.page.locator('input[name=plugins][value=root]').uncheck()
        self.assertFalse(self.page.locator('#capabilityApply').is_disabled())
        self.assertTrue(self.page.locator('#capabilityDraftStatus').is_visible())
        self.page.locator('#closeCapabilities').click()
        self.assertEqual(self.page.evaluate('state.config.enabledPlugins'),['device','screen','root'])
        self.assertEqual(self.page.evaluate("testPackets.filter(p=>p.method==='setCapabilities').length"),0)
        self.page.locator('#composerTools').click()
        self.page.locator('[data-capability-tab=plugins]').click()
        self.assertTrue(self.page.locator('input[name=plugins][value=root]').is_checked())
        self.assertEqual(self.errors,[])

    def test_native_inventory_controls_tool_count_and_disabled_device_actions(self):
        self.setup_bridge({'availableTools':{'count':2,'names':['get_device_state','list_apps']}})
        self.page.locator('#composerTools').click()
        self.assertIn('도구 2개',self.page.locator('#capabilitySavedStatus').inner_text())
        self.assertEqual(self.page.locator('#capabilityToolNames p').count(),2)
        self.page.locator('[data-capability-tab=plugins]').click()
        self.page.locator('input[name=plugins][value=root]').uncheck()
        self.assertIn('도구 2개',self.page.locator('#capabilitySavedStatus').inner_text())
        self.page.locator('#closeCapabilities').click();self.navigate('device')
        self.assertTrue(self.page.locator('#applyVolume').is_disabled())
        self.assertTrue(self.page.locator('#applyBrightness').is_disabled())
        self.assertTrue(self.page.locator('#rootProcesses').is_disabled())
        self.assertFalse(self.page.locator('#executeTool').is_disabled())
        self.assertTrue(self.page.locator('#toolSelect option[value=set_volume]').evaluate('(e)=>e.disabled'))
        self.assertEqual(self.errors,[])

    def test_web_key_saves_separately_and_preserves_unsaved_model_api_key(self):
        self.setup_bridge();self.navigate('settings');self.page.locator('#settingsConnection').click();self.open_provider_details()
        self.page.locator('#token').fill('unsaved-model-fixture-secret')
        self.page.locator('#menuToggle').click();self.page.locator('#settingsToolsHome').click();self.page.locator('#settingsWeb').click()
        self.page.evaluate("""() => {const base=NativeBridge.postMessage;NativeBridge.postMessage=raw=>{const p=JSON.parse(raw);if(p.method!=='setCapabilities')return base(raw);testPackets.push(p);testConfig={...testConfig,...p.data,hasWebToken:!!p.data.webToken};delete testConfig.webToken;setTimeout(()=>PocketNative({id:p.id,ok:true,data:testConfig}),0);};}""")
        self.page.locator('#webProvider').select_option('tavily');self.page.locator('#webPluginEnabled').check();self.page.locator('#webToken').fill('fixture-tavily-secret');self.page.locator('#saveWebSettings').click()
        self.page.wait_for_function('() => state.config.hasWebToken === true')
        packet=self.page.evaluate("testPackets.find(p=>p.method==='setCapabilities').data")
        self.assertEqual(packet['webProvider'],'tavily');self.assertEqual(packet['webToken'],'fixture-tavily-secret')
        self.assertNotIn('token',packet);self.assertNotIn('endpoint',packet);self.assertNotIn('model',packet)
        self.assertEqual(self.page.locator('#token').input_value(),'unsaved-model-fixture-secret')
        self.assertEqual(self.page.locator('#webToken').input_value(),'')
        self.assertEqual(self.page.evaluate('state.config.model'),'model-0')
        self.assertIn('암호화',self.page.locator('#webTokenStatus').inner_text())
        self.assertEqual(self.errors,[])

    def test_skill_editor_save_read_and_confirmed_delete_native_requests(self):
        self.setup_bridge()
        self.page.evaluate("""() => {window.fixtureSkills=[];const base=NativeBridge.postMessage;NativeBridge.postMessage=raw=>{const p=JSON.parse(raw);let data;
          if(p.method==='skillsList')data=fixtureSkills;
          else if(p.method==='skillsSave'){fixtureSkills=[{name:p.data.name,description:p.data.description,body:p.data.content}];data={saved:true,name:p.data.name,skills:fixtureSkills};}
          else if(p.method==='skillsRead')data=fixtureSkills[0];
          else if(p.method==='skillsDelete'){fixtureSkills=[];data={deleted:true,skills:[]};}
          else return base(raw);testPackets.push(p);setTimeout(()=>PocketNative({id:p.id,ok:true,data}),0);};}""")
        self.navigate('settings');self.page.locator('#settingsSkills').click();self.page.locator('#newSkill').click()
        self.page.locator('#skillName').fill('my-summary');self.page.locator('#skillDescription').fill('요약 스킬');self.page.locator('#skillContent').fill('# 지침\n핵심을 요약합니다.')
        self.page.locator('#saveSkill').click();self.page.wait_for_function("() => testPackets.some(p=>p.method==='skillsSave')")
        self.page.wait_for_function("() => document.getElementById('skillStatus').textContent.includes('SKILL.md')")
        packet=self.page.evaluate("testPackets.find(p=>p.method==='skillsSave').data")
        self.assertEqual(packet,{'name':'my-summary','description':'요약 스킬','content':'# 지침\n핵심을 요약합니다.'})
        self.page.locator('#newSkill').click();self.page.locator('#savedSkills summary').click();self.page.locator('#savedSkills [data-skill-action=edit]').click()
        self.page.wait_for_function("() => document.getElementById('skillContent').value.includes('핵심')")
        self.assertTrue(self.page.locator('#skillName').evaluate('(e)=>e.readOnly'))
        self.page.once('dialog',lambda dialog:dialog.accept());self.page.locator('#deleteSkill').click()
        self.page.wait_for_function("() => testPackets.some(p=>p.method==='skillsDelete')")
        self.assertEqual(self.page.evaluate('fixtureSkills'),[])
        self.assertEqual(self.errors,[])

    def test_drawer_settings_stays_at_bottom_without_footer_badges(self):
        for design in ('white','black'):
            self.page.evaluate('(id)=>applyDesign(id)',design)
            self.page.locator('#menuToggle').click()
            self.assertEqual(self.page.locator('.sidebar-footer,#connectionPill,#designShortcut').count(),0)
            self.assertEqual(self.page.locator('#sidebar .drawer-nav button').count(),1)
            drawer=self.page.locator('#sidebar').bounding_box();button=self.page.locator('#sidebar [data-page="settings"]').bounding_box()
            gap=drawer['y']+drawer['height']-button['y']-button['height']
            self.assertGreaterEqual(gap,0);self.assertLessEqual(gap,40)
            self.page.locator('#closeSidebar').click()
        self.assertEqual(self.errors,[])

    def test_compact_settings_nested_back_returns_to_tools_or_advanced(self):
        self.setup_bridge();self.navigate('settings')
        self.assertEqual(self.page.locator('#settingsHome .settings-menu-row:visible').count(),8)
        self.assertTrue(self.page.locator('#settingsTerminal').is_visible())
        self.assertFalse(self.page.locator('#settingsWeb').is_visible())
        self.assertFalse(self.page.locator('#settingsHistory').is_visible())
        self.page.locator('#settingsToolsHome').click()
        self.page.locator('#settingsWeb').click()
        self.assertTrue(self.page.locator('#webSettingsForm').is_visible())
        self.page.locator('#menuToggle').click()
        self.assertTrue(self.page.locator('#settingsPanelTools').is_visible())
        self.page.locator('#settingsTools').click()
        self.assertTrue(self.page.locator('#page-device').is_visible())
        self.page.locator('#menuToggle').click()
        self.assertTrue(self.page.locator('#settingsPanelTools').is_visible())
        self.page.locator('#menuToggle').click()
        self.assertTrue(self.page.locator('#settingsHome').is_visible())
        self.page.locator('#settingsAbout').click()
        self.page.locator('#settingsHistory').click()
        self.assertTrue(self.page.locator('#page-history').is_visible())
        self.page.locator('#menuToggle').click()
        self.assertTrue(self.page.locator('#settingsPanelAbout').is_visible())
        self.page.locator('#menuToggle').click()
        self.assertTrue(self.page.locator('#settingsHome').is_visible())
        self.assertEqual(self.errors,[])

    def test_folder_picker_readonly_revocation_preserves_model_secret_draft(self):
        self.setup_bridge();self.navigate('settings');self.page.locator('#settingsConnection').click();self.open_provider_details()
        self.page.locator('#token').fill('unsaved-provider-fixture-secret')
        self.navigate('permissions')
        self.assertFalse(self.page.locator('#toolSelect').is_visible())
        self.assertIn('선택',self.page.locator('#filesFolderStatus').inner_text())
        self.assertFalse(self.page.locator('#revokeFilesFolder').is_visible())
        self.page.evaluate("""() => {const base=NativeBridge.postMessage;NativeBridge.postMessage=raw=>{const p=JSON.parse(raw);if(!['chooseFilesFolder','revokeFilesFolder'].includes(p.method))return base(raw);testPackets.push(p);const chosen=p.method==='chooseFilesFolder';const data={configured:chosen,readable:chosen,writable:false,displayName:chosen?'Selected fixture folder':'',config:{...testConfig,enabledPlugins:chosen?['device','screen','root','files']:['device','screen','root']}};setTimeout(()=>PocketNative({id:p.id,ok:true,data}),0);};}""")
        self.page.locator('#chooseFilesFolder').click();self.page.wait_for_function('() => state.files.configured === true')
        self.assertEqual(self.page.locator('#filesBadge').inner_text(),'읽기')
        self.assertIn('읽기만 가능',self.page.locator('#filesFolderStatus').inner_text())
        self.assertEqual(self.page.locator('#token').input_value(),'unsaved-provider-fixture-secret')
        self.assertEqual(self.page.evaluate("testPackets.find(p=>p.method==='chooseFilesFolder').data"),{})
        self.page.evaluate("PocketNative({event:'files',data:{configured:true,readable:false,writable:false,permissionLost:true}})")
        self.assertEqual(self.page.locator('#filesBadge').inner_text(),'권한 필요')
        self.assertIn('만료',self.page.locator('#filesFolderStatus').inner_text())
        self.page.locator('#revokeFilesFolder').click();self.page.wait_for_function('() => state.files.configured === false')
        self.assertEqual(self.page.locator('#filesBadge').inner_text(),'선택 전')
        self.assertFalse(self.page.locator('#revokeFilesFolder').is_visible())
        self.assertNotIn('files',self.page.evaluate('state.config.enabledPlugins'))
        self.assertEqual(self.page.locator('#token').input_value(),'unsaved-provider-fixture-secret')
        self.assertEqual(self.errors,[])

    def test_cancelled_folder_picker_retains_authoritative_existing_grant(self):
        self.setup_bridge();self.navigate('permissions')
        self.page.evaluate("""() => {const grant={configured:true,readable:true,writable:true,displayName:'Existing fixture folder'};updateFilesStatus(grant);const base=NativeBridge.postMessage;NativeBridge.postMessage=raw=>{const p=JSON.parse(raw);if(p.method!=='chooseFilesFolder')return base(raw);testPackets.push(p);setTimeout(()=>PocketNative({id:p.id,ok:true,data:{...grant,cancelled:true}}),0);};}""")
        self.page.locator('#chooseFilesFolder').click();self.page.wait_for_function('() => !state.filesSaving')
        self.assertEqual(self.page.locator('#filesFolderStatus').inner_text(),'Existing fixture folder')
        self.assertEqual(self.page.locator('#filesBadge').inner_text(),'읽기·쓰기')
        self.assertNotIn('선택한 폴더에만 접근',self.page.locator('#toast').inner_text())
        self.page.evaluate("PocketNative({event:'started',data:{session:'busy-files',text:'question'}})")
        self.assertTrue(self.page.locator('#chooseFilesFolder').is_disabled())
        self.assertTrue(self.page.locator('#revokeFilesFolder').is_disabled())
        self.assertEqual(self.errors,[])

    def test_global_control_and_approval_mode_save_independently_without_credentials(self):
        self.setup_bridge({'deviceScope':'all','approvalMode':'ask'});self.navigate('settings');self.page.locator('#settingsConnection').click();self.open_provider_details()
        self.page.locator('#token').fill('unsaved-policy-test-secret');self.navigate('permissions')
        self.assertEqual(self.page.locator('#allowedApps').count(),0)
        self.assertTrue(self.page.locator('#deviceScopeAll').is_checked())
        self.page.locator('#approvalMode').select_option('auto')
        self.page.wait_for_function("() => state.config.approvalMode === 'auto'")
        self.assertEqual(self.page.evaluate("testPackets.filter(p=>p.method==='setCapabilities').at(-1).data"),{'approvalMode':'auto'})
        self.page.locator('#deviceScopeAll').uncheck();self.page.wait_for_function("() => state.config.deviceScope === 'none'")
        self.assertEqual(self.page.evaluate("testPackets.filter(p=>p.method==='setCapabilities').at(-1).data"),{'deviceScope':'none'})
        self.assertEqual(self.page.evaluate('state.config.approvalMode'),'auto')
        self.assertEqual(self.page.locator('#token').input_value(),'unsaved-policy-test-secret')
        self.assertEqual(self.page.evaluate('state.config.model'),'model-0')
        self.page.evaluate('boot()');self.page.wait_for_function("() => document.getElementById('approvalMode').value === 'auto'")
        self.assertFalse(self.page.locator('#deviceScopeAll').is_checked())
        self.assertEqual(self.errors,[])

    def test_global_app_selection_does_not_require_legacy_individual_allowlist(self):
        self.setup_bridge({'deviceScope':'all','approvalMode':'ask','allowedApps':[]})
        self.page.evaluate("""() => {const base=NativeBridge.postMessage;NativeBridge.postMessage=raw=>{const p=JSON.parse(raw);if(p.method!=='apps')return base(raw);testPackets.push(p);setTimeout(()=>PocketNative({id:p.id,ok:true,data:[{package:'dev.hermesfixture.android',label:'Independent fixture',allowed:false,protected:false,system:false}]}),0);};}""")
        self.navigate('device');self.page.locator('#toolSelect').select_option('launch_app')
        self.page.wait_for_function('() => !manualToolState.loadingApps')
        self.assertEqual(self.page.locator('#manual_package option[value="dev.hermesfixture.android"]').count(),1)
        self.assertEqual(self.page.evaluate('state.config.allowedApps'),[])
        self.assertEqual(self.page.locator('#allowedApps').count(),0)
        self.assertEqual(self.page.evaluate("testPackets.filter(p=>p.method==='runTool'&&p.data.name==='launch_app').length"),0)
        self.assertEqual(self.errors,[])

    def test_portrait_approval_selector_keeps_label_and_options_inside_row(self):
        self.setup_bridge({'deviceScope':'all','approvalMode':'ask'})
        self.navigate('permissions')
        for width in (320,360,393):
            self.page.set_viewport_size({'width':width,'height':740})
            for mode in ('ask','auto'):
                self.page.locator('#approvalMode').select_option(mode)
                self.page.wait_for_function('(mode) => state.config.approvalMode === mode',arg=mode)
                bounds=self.page.locator('#approvalMode').evaluate('''e=>{
                    const row=e.closest('.setting-row'),label=row.querySelector('.row-text');
                    const r=row.getBoundingClientRect(),s=e.getBoundingClientRect(),l=label.getBoundingClientRect();
                    return {left:r.left,right:r.right,selectLeft:s.left,selectRight:s.right,
                        labelLeft:l.left,labelRight:l.right,labelTop:l.top,labelBottom:l.bottom,
                        selectTop:s.top,selectBottom:s.bottom,scroll:document.documentElement.scrollWidth};
                }''')
                self.assertLessEqual(bounds['scroll'],width)
                self.assertGreaterEqual(bounds['selectLeft'],bounds['left'])
                self.assertLessEqual(bounds['selectRight'],bounds['right'])
                self.assertGreaterEqual(bounds['labelLeft'],bounds['left'])
                self.assertLessEqual(bounds['labelRight'],bounds['right'])
                overlaps=(bounds['labelLeft']<bounds['selectRight'] and bounds['labelRight']>bounds['selectLeft']
                          and bounds['labelTop']<bounds['selectBottom'] and bounds['labelBottom']>bounds['selectTop'])
                self.assertFalse(overlaps,'approval label overlaps the selected option')
        self.assertEqual(self.errors,[])

    def test_floating_toggle_saves_only_preference_and_hydrates_after_reopen(self):
        self.setup_bridge({'floatingEnabled':True,'approvalMode':'auto'})
        self.navigate('settings');self.page.locator('#settingsConnection').click();self.open_provider_details()
        self.page.locator('#token').fill('unsaved-floating-fixture-secret');self.navigate('permissions')
        self.assertTrue(self.page.locator('#floatingEnabled').is_checked())
        self.page.locator('#floatingEnabled').uncheck()
        self.page.wait_for_function('() => !preferenceSaving && state.config.floatingEnabled === false')
        self.assertEqual(self.page.evaluate("testPackets.filter(p=>p.method==='setCapabilities').at(-1).data"),{'floatingEnabled':False})
        self.assertIn('꺼짐',self.page.locator('#floatingStatus').inner_text())
        self.assertEqual(self.page.locator('#token').input_value(),'unsaved-floating-fixture-secret')
        self.assertEqual(self.page.evaluate('state.config.approvalMode'),'auto')
        self.page.evaluate('boot()')
        self.page.wait_for_function('() => !document.getElementById("floatingEnabled").checked')
        self.page.locator('#floatingEnabled').check()
        self.page.wait_for_function('() => !preferenceSaving && state.config.floatingEnabled === true')
        self.assertEqual(self.page.evaluate("testPackets.filter(p=>p.method==='setCapabilities').at(-1).data"),{'floatingEnabled':True})
        self.assertEqual(self.errors,[])

    def test_floating_pending_rejection_and_busy_preserve_saved_state(self):
        self.setup_bridge({'floatingEnabled':True});self.navigate('permissions')
        self.page.evaluate('''() => {const base=NativeBridge.postMessage;NativeBridge.postMessage=raw=>{
            const p=JSON.parse(raw);if(p.method!=='setCapabilities')return base(raw);
            testPackets.push(p);window.pendingFloating=p;
        };}''')
        self.page.locator('#floatingEnabled').uncheck()
        self.assertTrue(self.page.locator('#floatingEnabled').is_disabled())
        self.page.evaluate("PocketNative({id:pendingFloating.id,ok:false,data:{message:'fixture floating save rejected'}})")
        self.page.wait_for_function('() => !preferenceSaving')
        self.assertTrue(self.page.locator('#floatingEnabled').is_checked())
        self.assertTrue(self.page.evaluate('state.config.floatingEnabled'))
        self.page.evaluate("PocketNative({event:'started',data:{session:'floating-busy',text:'question'}})")
        self.assertTrue(self.page.locator('#floatingEnabled').is_disabled())
        self.assertEqual(self.errors,[])

    def test_screen_capture_capability_states_do_not_claim_permission_is_actual_capture(self):
        self.setup_bridge();self.navigate('permissions')
        self.page.evaluate("updateDevice({accessibility:true,screenshotSupported:true,screenshotCapability:true,screenshotAvailable:true})")
        self.assertIn('권한 연결',self.page.locator('#screenCaptureBadge').inner_text())
        self.assertNotIn('캡처 완료',self.page.locator('#screenCaptureStatus').inner_text())
        self.page.evaluate("updateDevice({accessibility:true,screenshotSupported:true,screenshotCapability:false,screenshotAvailable:false})")
        self.assertIn('재연결 필요',self.page.locator('#screenCaptureBadge').inner_text())
        self.page.evaluate("updateDevice({accessibility:true,screenshotSupported:false,screenshotCapability:false,screenshotAvailable:false})")
        self.assertIn('미지원',self.page.locator('#screenCaptureBadge').inner_text())
        self.assertEqual(self.errors,[])

    def test_pending_and_failed_device_preference_restore_saved_state(self):
        self.setup_bridge({'deviceScope':'all','approvalMode':'ask'});self.navigate('permissions')
        self.page.evaluate("""() => {const base=NativeBridge.postMessage;NativeBridge.postMessage=raw=>{const p=JSON.parse(raw);if(p.method!=='setCapabilities')return base(raw);testPackets.push(p);window.pendingDevicePreference=p;};}""")
        self.page.locator('#approvalMode').select_option('auto')
        self.assertTrue(self.page.locator('#approvalMode').is_disabled());self.assertTrue(self.page.locator('#deviceScopeAll').is_disabled())
        self.page.evaluate("PocketNative({id:pendingDevicePreference.id,ok:false,data:{message:'fixture save rejected'}})")
        self.page.wait_for_function('() => !preferenceSaving')
        self.assertEqual(self.page.locator('#approvalMode').input_value(),'ask')
        self.assertEqual(self.page.evaluate('state.config.approvalMode'),'ask');self.assertTrue(self.page.locator('#deviceScopeAll').is_checked())
        self.page.evaluate("PocketNative({event:'started',data:{session:'policy-busy',text:'question'}})")
        self.assertTrue(self.page.locator('#approvalMode').is_disabled());self.assertTrue(self.page.locator('#deviceScopeAll').is_disabled())
        self.assertEqual(self.errors,[])

    def test_keyless_web_save_omits_tavily_secret_and_preserves_unsaved_key(self):
        self.setup_bridge({'webProvider':'tavily','hasWebToken':True});self.navigate('settings')
        self.page.locator('#settingsToolsHome').click();self.page.locator('#settingsWeb').click()
        self.assertEqual(self.page.locator('#webProvider option').count(),2)
        self.page.locator('#webToken').fill('unsaved-tavily-fixture-secret')
        self.page.locator('#clearWebToken').check();self.page.locator('#webProvider').select_option('mwmbl')
        self.assertFalse(self.page.locator('#webTavilyFields').is_visible())
        self.assertIn('제한',self.page.locator('#webProviderHelp').inner_text())
        self.page.locator('#webPluginEnabled').check();self.page.locator('#saveWebSettings').click()
        self.page.wait_for_function("() => state.config.webProvider === 'mwmbl'")
        packet=self.page.evaluate("testPackets.filter(p=>p.method==='setCapabilities').at(-1).data")
        self.assertEqual(packet['webProvider'],'mwmbl');self.assertNotIn('webToken',packet);self.assertNotIn('clearWebToken',packet)
        self.assertNotIn('token',packet);self.assertNotIn('endpoint',packet)
        self.assertTrue(self.page.evaluate('state.config.hasWebToken'))
        self.page.locator('#webProvider').select_option('tavily')
        self.assertEqual(self.page.locator('#webToken').input_value(),'unsaved-tavily-fixture-secret')
        self.assertEqual(self.errors,[])

    def test_shizuku_needs_live_verified_service_and_shell_is_not_root(self):
        self.setup_bridge();self.navigate('permissions')
        self.page.evaluate("updateShizuku({enabled:true,installed:true,binderAlive:true,permissionGranted:true,serviceConnected:false,uid:2000,available:false,state:'connecting',reason:'서비스 연결 대기'})")
        self.assertNotIn('연결됨',self.page.locator('#shizukuStatus').inner_text())
        self.page.evaluate("updateShizuku({enabled:true,installed:true,binderAlive:true,permissionGranted:true,serviceConnected:true,uid:2000,available:true,state:'ready_shell'})")
        self.assertIn('Shell UID 2000',self.page.locator('#shizukuStatus').inner_text())
        self.assertNotIn('Root',self.page.locator('#shizukuStatus').inner_text())
        self.assertIn('su Root 권한은 확인되지 않았습니다',self.page.locator('#rootSourceStatus').inner_text())
        self.assertIn('Shizuku Shell UID 2000 연결됨',self.page.locator('#rootSourceStatus').inner_text())
        self.page.evaluate("updateDevice({...state.device,root:true})")
        self.assertIn('su로 실제 UID 0 권한을 확인',self.page.locator('#rootSourceStatus').inner_text())
        self.page.evaluate("updateShizuku({enabled:true,installed:true,binderAlive:true,permissionGranted:true,serviceConnected:true,uid:12345,available:true,reason:'UID 검증 실패'})")
        self.assertNotIn('연결됨',self.page.locator('#shizukuStatus').inner_text())
        self.assertNotIn('Shizuku Shell UID 2000 연결됨',self.page.locator('#rootSourceStatus').inner_text())
        self.assertEqual(self.errors,[])

    def test_shizuku_toggle_and_os_permission_request_never_forward_model_credentials(self):
        self.setup_bridge({'shizukuEnabled':False});self.navigate('settings');self.page.locator('#settingsConnection').click();self.open_provider_details()
        self.page.locator('#token').fill('unsaved-shizuku-model-secret');self.navigate('permissions')
        self.page.evaluate("""() => {const base=NativeBridge.postMessage;NativeBridge.postMessage=raw=>{const p=JSON.parse(raw);if(!['setShizuku','requestShizukuPermission'].includes(p.method))return base(raw);testPackets.push(p);const s={enabled:true,installed:p.method==='requestShizukuPermission',binderAlive:p.method==='requestShizukuPermission',permissionGranted:false,serviceConnected:false,available:false,reason:p.method==='setShizuku'?'Shizuku 설치 필요':'Shizuku 권한 필요'};setTimeout(()=>PocketNative({id:p.id,ok:true,data:{config:{...testConfig,shizukuEnabled:true},shizuku:s}}),0);};}""")
        self.page.locator('#shizukuEnabled').check();self.page.wait_for_function('() => !state.shizukuSaving')
        self.assertEqual(self.page.evaluate("testPackets.find(p=>p.method==='setShizuku').data"),{'enabled':True})
        self.assertIn('설치 필요',self.page.locator('#shizukuStatus').inner_text())
        self.assertFalse(self.page.locator('#requestShizukuPermission').is_visible())
        self.page.evaluate("PocketNative({event:'shizuku',data:{enabled:true,installed:true,binderAlive:true,permissionGranted:false,serviceConnected:false,available:false,state:'permission_required'}})")
        self.page.locator('#requestShizukuPermission').click();self.page.wait_for_function('() => !state.shizukuSaving')
        self.assertEqual(self.page.evaluate("testPackets.find(p=>p.method==='requestShizukuPermission').data"),{})
        self.assertNotIn('연결됨',self.page.locator('#shizukuStatus').inner_text())
        self.assertEqual(self.page.locator('#token').input_value(),'unsaved-shizuku-model-secret')
        self.assertEqual(self.errors,[])

    def test_busy_blocks_preference_and_model_controls(self):
        self.setup_bridge()
        self.page.evaluate("PocketNative({event:'started',data:{session:'busy',text:'question'}})")
        self.assertTrue(self.page.locator('#composerTools').is_disabled())
        self.assertTrue(self.page.locator('#composerConnection').is_disabled())
        self.assertTrue(self.page.locator('#reasoningPicker').is_disabled())
        self.page.evaluate('openCapabilities();openModels();openReasoning()')
        self.assertFalse(self.page.locator('#capabilitySheet').is_visible())
        self.assertFalse(self.page.locator('#modelSheet').is_visible())
        self.assertFalse(self.page.locator('#reasoningSheet').is_visible())
        self.assertEqual(self.page.evaluate("testPackets.filter(p=>p.method==='setCapabilities'||p.method==='listModels').length"),0)
        self.assertEqual(self.errors,[])
