package dev.chanho.hermes.tests;
import android.app.*;
import android.os.*;
import android.content.*;
import android.view.*;
import android.webkit.*;
import android.util.Base64;
import java.io.ByteArrayOutputStream;
import java.util.concurrent.*;
import java.lang.reflect.*;
import org.json.*;
import java.util.concurrent.atomic.*;
public final class PocketProbeInstrumentation extends Instrumentation {
    private String script;
    private final BlockingQueue<String> replies=new LinkedBlockingQueue<>();
    public final class ProbeBridge { @JavascriptInterface public void report(String value){replies.offer(value);} }
    @Override public void onCreate(Bundle args){script=new String(Base64.decode(args.getString("script",""),Base64.DEFAULT),java.nio.charset.StandardCharsets.UTF_8);start();}
    private WebView find(View v){if(v instanceof WebView)return (WebView)v;if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++){WebView w=find(g.getChildAt(i));if(w!=null)return w;}}return null;}
    private Object field(Object target,String name)throws Exception {Field f=target.getClass().getDeclaredField(name);f.setAccessible(true);return f.get(target);}
    private Object call(Object target,String name,Class<?>[] types,Object...args)throws Exception {Method m=target.getClass().getDeclaredMethod(name,types);m.setAccessible(true);return m.invoke(target,args);}
    private String javascript(WebView web,String code)throws Exception {
        AtomicReference<String> value=new AtomicReference<>();CountDownLatch ready=new CountDownLatch(1);
        runOnMainSync(()->web.evaluateJavascript(code,result->{value.set(result);ready.countDown();}));
        if(!ready.await(5,TimeUnit.SECONDS))throw new IllegalStateException("JavaScript evaluation timeout");return value.get();
    }
    private boolean imeVisible(WebView web){AtomicBoolean shown=new AtomicBoolean();runOnMainSync(()->{WindowInsets insets=web.getRootWindowInsets();shown.set(insets!=null&&insets.isVisible(WindowInsets.Type.ime()));});return shown.get();}
    private JSONObject newChatIme(Activity activity,WebView web)throws Exception {
        Thread.sleep(2500);
        JSONObject point=new JSONObject(javascript(web,"(()=>{const r=document.getElementById('messageInput').getBoundingClientRect();return {x:r.left+r.width/2,y:r.top+r.height/2,width:innerWidth};})()"));
        int[] location=new int[2];AtomicInteger width=new AtomicInteger();runOnMainSync(()->{web.getLocationOnScreen(location);width.set(web.getWidth());});
        float scale=(float)(width.get()/point.getDouble("width")),x=location[0]+(float)point.getDouble("x")*scale,y=location[1]+(float)point.getDouble("y")*scale;
        long now=SystemClock.uptimeMillis();sendPointerSync(MotionEvent.obtain(now,now,MotionEvent.ACTION_DOWN,x,y,0));sendPointerSync(MotionEvent.obtain(now,now+80,MotionEvent.ACTION_UP,x,y,0));
        for(int i=0;i<40&&!imeVisible(web);i++)Thread.sleep(100);
        boolean before=imeVisible(web);String beforeFocus=javascript(web,"document.activeElement.id");
        javascript(web,"document.getElementById('headerNewChat').click();true");
        for(int i=0;i<40&&imeVisible(web);i++)Thread.sleep(100);Thread.sleep(250);
        return new JSONObject().put("actualImeVisibleBefore",before).put("actualImeHiddenAfter",!imeVisible(web)).put("focusBefore",beforeFocus).put("focusAfter",javascript(web,"document.activeElement.id")).put("inputEmptyAfter",javascript(web,"document.getElementById('messageInput').value===''"));
    }
    private JSONObject queuedCancel(Activity activity)throws Exception {
        Object runtime=field(activity,"runtime"),tools=field(runtime,"tools");JSONObject result=new JSONObject();
        for(boolean stopInstead:new boolean[]{false,true}){
            ((AtomicBoolean)field(runtime,"stop")).set(false);CountDownLatch blocked=new CountDownLatch(1),release=new CountDownLatch(1);AtomicInteger calls=new AtomicInteger();AtomicReference<String> error=new AtomicReference<>();
            new Handler(Looper.getMainLooper()).post(()->{blocked.countDown();try{release.await(1500,TimeUnit.MILLISECONDS);}catch(InterruptedException ignored){}});
            if(!blocked.await(1,TimeUnit.SECONDS))throw new IllegalStateException("Main queue blocker not started");
            Thread caller=new Thread(()->{try{call(tools,"onMain",new Class<?>[]{Callable.class},(Callable<JSONObject>)()->{calls.incrementAndGet();return new JSONObject().put("ran",true);});}catch(Exception e){error.set(e.toString());}},"ActualDeviceToolsQueuedCaller");caller.start();
            for(int i=0;i<30&&caller.getState()!=Thread.State.TIMED_WAITING;i++)Thread.sleep(10);
            if(stopInstead)call(runtime,"stopAll",new Class<?>[]{});else caller.interrupt();Thread.sleep(60);release.countDown();caller.join(1500);Thread.sleep(100);
            result.put(stopInstead?"runtimeStopPreventsLateAction":"callerInterruptCancelsQueuedAction",calls.get()==0&&!caller.isAlive()&&error.get()!=null);
        }
        call(runtime,"localTool",new Class<?>[]{String.class,JSONObject.class,String.class},"get_device_state",new JSONObject(),"probe-queue-reset");AtomicBoolean busy=(AtomicBoolean)field(runtime,"busy");for(int i=0;i<100&&busy.get();i++)Thread.sleep(30);
        result.put("readonlyEntrySettlesAfterTest",!busy.get());return result;
    }
    private JSONObject lifecycle(Activity activity,WebView original)throws Exception {
        Object runtime=field(activity,"runtime"),net=field(runtime,"net"),store=field(runtime,"store");
        JSONObject config=(JSONObject)call(store,"config",new Class<?>[]{});JSONArray prior=config.getJSONArray("enabledPlugins");
        call(store,"saveCapabilities",new Class<?>[]{JSONObject.class},new JSONObject().put("enabledPlugins",new JSONArray().put("device").put("screen").put("root").put("agent").put("web")));
        call(runtime,"stopAll",new Class<?>[]{});
        boolean stopped=(Boolean)call(net,"cancelled",new Class<?>[]{});
        call(runtime,"localTool",new Class<?>[]{String.class,JSONObject.class,String.class},"get_device_state",new JSONObject(),"probe-cancel-reset");
        boolean reset=!(Boolean)call(net,"cancelled",new Class<?>[]{});
        AtomicBoolean busy=(AtomicBoolean)field(runtime,"busy");for(int i=0;i<100&&busy.get();i++)Thread.sleep(50);
        boolean settled=!busy.get();
        JSONArray audit=(JSONArray)call(store,"audit",new Class<?>[]{});boolean completed=false;
        for(int i=0;i<audit.length();i++){JSONObject item=audit.getJSONObject(i);if("get_device_state".equals(item.optString("tool"))&&"completed".equals(item.optString("status")))completed=true;}
        call(store,"saveCapabilities",new Class<?>[]{JSONObject.class},new JSONObject().put("enabledPlugins",prior));
        runOnMainSync(()->original.loadUrl("chrome://crash"));
        AtomicReference<WebView> replacement=new AtomicReference<>();
        for(int i=0;i<150;i++){runOnMainSync(()->replacement.set(find(activity.getWindow().getDecorView())));if(replacement.get()!=null&&replacement.get()!=original)break;Thread.sleep(100);}
        WebView recovered=replacement.get();if(recovered==null||recovered==original)throw new IllegalStateException("Actual renderer crash did not produce replacement WebView");Thread.sleep(2500);
        AtomicReference<String> url=new AtomicReference<>();AtomicBoolean detached=new AtomicBoolean();runOnMainSync(()->{url.set(recovered.getUrl());detached.set(original.getParent()==null);});
        return new JSONObject().put("stopCancelsNet",stopped).put("manualEntryResetsNet",reset).put("manualBusySettled",settled).put("readonlyToolCompletedAudit",completed).put("rendererActuallyReplaced",true).put("oldViewDetached",detached.get()).put("activityAlive",!activity.isFinishing()&&!activity.isDestroyed()).put("runtimeIdentityPreserved",field(activity,"runtime")==runtime).put("recoveredUrl",url.get());
    }
    private void dumpNode(android.view.accessibility.AccessibilityNodeInfo n,org.xmlpull.v1.XmlSerializer x)throws Exception {
        if(n==null)return;x.startTag(null,"node");android.graphics.Rect b=new android.graphics.Rect();n.getBoundsInScreen(b);
        x.attribute(null,"text",n.getText()==null?"":n.getText().toString());x.attribute(null,"content-desc",n.getContentDescription()==null?"":n.getContentDescription().toString());x.attribute(null,"password",String.valueOf(n.isPassword()));x.attribute(null,"bounds","["+b.left+","+b.top+"]["+b.right+","+b.bottom+"]");
        for(int i=0;i<n.getChildCount();i++){android.view.accessibility.AccessibilityNodeInfo c=n.getChild(i);if(c!=null){dumpNode(c,x);c.recycle();}}x.endTag(null,"node");
    }
    private void dumpAutomation()throws Exception {
        UiAutomation automation=getUiAutomation(UiAutomation.FLAG_DONT_SUPPRESS_ACCESSIBILITY_SERVICES);android.accessibilityservice.AccessibilityServiceInfo info=automation.getServiceInfo();info.flags|=android.accessibilityservice.AccessibilityServiceInfo.FLAG_RETRIEVE_INTERACTIVE_WINDOWS;automation.setServiceInfo(info);
        java.io.StringWriter w=new java.io.StringWriter();org.xmlpull.v1.XmlSerializer x=android.util.Xml.newSerializer();x.setOutput(w);x.startTag(null,"hierarchy");
        java.util.List<android.view.accessibility.AccessibilityWindowInfo> windows=automation.getWindows();
        for(android.view.accessibility.AccessibilityWindowInfo window:windows){android.view.accessibility.AccessibilityNodeInfo n=window.getRoot();if(n!=null)try{dumpNode(n,x);}finally{n.recycle();}window.recycle();}
        x.endTag(null,"hierarchy");x.flush();java.io.File f=new java.io.File(getTargetContext().getExternalFilesDir(null),"probe-ui.xml"),temp=new java.io.File(f.getParentFile(),"probe-ui.tmp");try(java.io.FileWriter fw=new java.io.FileWriter(temp)){fw.write(w.toString());}temp.renameTo(f);
    }
    private JSONObject actualWindowDiagnostics()throws Exception {
        Thread.sleep(12000);Class<?> type=Class.forName("dev.chanho.hermes.PhoneAccessibilityService");Method current=type.getDeclaredMethod("current");current.setAccessible(true);Object service=current.invoke(null);
        if(service==null)return new JSONObject().put("serviceBound",false);
        AtomicReference<JSONObject> result=new AtomicReference<>();runOnMainSync(()->{try{org.json.JSONArray entries=new org.json.JSONArray();java.util.List<android.view.accessibility.AccessibilityWindowInfo> list=(java.util.List<android.view.accessibility.AccessibilityWindowInfo>)service.getClass().getMethod("getWindows").invoke(service);
            for(android.view.accessibility.AccessibilityWindowInfo w:list){android.graphics.Rect b=new android.graphics.Rect();w.getBoundsInScreen(b);android.view.accessibility.AccessibilityNodeInfo root=w.getRoot();String pkg=root==null?"":String.valueOf(root.getPackageName());android.graphics.Rect rb=new android.graphics.Rect();if(root!=null){root.getBoundsInScreen(rb);root.recycle();}entries.put(new JSONObject().put("title",String.valueOf(w.getTitle())).put("id",w.getId()).put("type",w.getType()).put("layer",w.getLayer()).put("active",w.isActive()).put("focused",w.isFocused()).put("bounds",b.toShortString()).put("rootBounds",rb.toShortString()).put("package",pkg));w.recycle();}result.set(new JSONObject().put("serviceBound",true).put("windows",entries));}catch(Exception e){try{result.set(new JSONObject().put("error",e.toString()));}catch(Exception ignored){}}});return result.get();
    }
    private JSONObject databaseBaseline(Activity activity)throws Exception {
        Object store=field(field(activity,"runtime"),"store");android.database.sqlite.SQLiteDatabase db=((android.database.sqlite.SQLiteOpenHelper)store).getWritableDatabase();
        String sid=(String)call(store,"newSession",new Class<?>[]{String.class},"PUBLIC_V1_MIGRATION_010");call(store,"message",new Class<?>[]{String.class,String.class,String.class},sid,"user","PUBLIC_LEGACY_MESSAGE_010");
        db.execSQL("INSERT OR REPLACE INTO transcripts(sid,body) VALUES(?,?)",new Object[]{sid,"PUBLIC_LEGACY_TRANSCRIPT_010"});JSONObject result=new JSONObject().put("version",db.getVersion()).put("sessionId",sid);org.json.JSONArray tables=new org.json.JSONArray();
        try(android.database.Cursor c=db.rawQuery("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name",null)){while(c.moveToNext())tables.put(c.getString(0));}result.put("tables",tables);
        for(String name:new String[]{"sessions","messages","transcripts","audit"})try(android.database.Cursor c=db.rawQuery("SELECT count(*) FROM "+name,null)){c.moveToFirst();result.put(name+"Count",c.getLong(0));}
        return result;
    }
    private JSONObject databaseTimeline(Activity activity,boolean readOnly)throws Exception {
        Object store=field(field(activity,"runtime"),"store");android.database.sqlite.SQLiteDatabase db=((android.database.sqlite.SQLiteOpenHelper)store).getWritableDatabase();java.io.File marker=new java.io.File(getTargetContext().getExternalFilesDir(null),"timeline-test.json");JSONObject ids;
        if(readOnly){try(java.io.FileReader r=new java.io.FileReader(marker)){StringBuilder text=new StringBuilder();char[] b=new char[1024];int n;while((n=r.read(b))!=-1)text.append(b,0,n);ids=new JSONObject(text.toString());}}
        else{
            String sid=(String)call(store,"newSession",new Class<?>[]{String.class},"PUBLIC_TIMELINE_NATIVE_010"),other=(String)call(store,"newSession",new Class<?>[]{String.class},"PUBLIC_TIMELINE_ISOLATED_010"),run="test_run_"+java.util.UUID.randomUUID();
            call(store,"message",new Class<?>[]{String.class,String.class,String.class},sid,"user","PUBLIC_TIMELINE_CHAT_010");
            JSONObject event=new JSONObject().put("runId",run).put("session",sid).put("toolCallId","call_public_a").put("kind","tool").put("name","terminal").put("status","started").put("summary","Public native step started").put("argsSummary","Android app UID; public marker command").put("seq",1).put("timestamp",1000).put("token","DO_NOT_STORE_RAW_PUBLIC_010").put("imageDataURL","DO_NOT_STORE_RAW_PUBLIC_010").put("rawReasoning","DO_NOT_STORE_RAW_PUBLIC_010").put("output","DO_NOT_STORE_RAW_PUBLIC_010").put("resourceContent","DO_NOT_STORE_RAW_PUBLIC_010");
            call(store,"recordActivity",new Class<?>[]{JSONObject.class},event);event.put("status","completed").put("seq",3).put("timestamp",2000).put("summary","Public native step completed");call(store,"recordActivity",new Class<?>[]{JSONObject.class},event);
            event.put("toolCallId","call_public_pending").put("status","started").put("seq",4).put("timestamp",2500).put("summary","Public pending step");call(store,"recordActivity",new Class<?>[]{JSONObject.class},event);
            event.put("session",other).put("runId",run+"_isolated").put("toolCallId","call_public_other").put("status","completed").put("seq",5).put("timestamp",3000);call(store,"recordActivity",new Class<?>[]{JSONObject.class},event);
            ids=new JSONObject().put("session",sid).put("otherSession",other).put("runId",run);try(java.io.FileWriter w=new java.io.FileWriter(marker)){w.write(ids.toString());}
        }
        JSONObject result=new JSONObject().put("version",db.getVersion()).put("ids",ids);org.json.JSONArray entries=(org.json.JSONArray)call(store,"activities",new Class<?>[]{String.class},ids.getString("session")),other=(org.json.JSONArray)call(store,"activities",new Class<?>[]{String.class},ids.getString("otherSession"));result.put("activities",entries).put("otherActivities",other);
        for(String name:new String[]{"sessions","messages","transcripts","audit","activities"})try(android.database.Cursor c=db.rawQuery("SELECT count(*) FROM "+name,null)){c.moveToFirst();result.put(name+"Count",c.getLong(0));}
        try(android.database.Cursor c=db.rawQuery("SELECT body FROM messages WHERE body='PUBLIC_LEGACY_MESSAGE_010'",null)){result.put("legacyMessagePreserved",c.moveToFirst());}
        try(android.database.Cursor c=db.rawQuery("SELECT body FROM transcripts WHERE body='PUBLIC_LEGACY_TRANSCRIPT_010'",null)){result.put("legacyTranscriptPreserved",c.moveToFirst());}
        org.json.JSONArray columns=new org.json.JSONArray();try(android.database.Cursor c=db.rawQuery("PRAGMA table_info(activities)",null)){while(c.moveToNext())columns.put(c.getString(1));}result.put("activityColumns",columns);result.put("rawFieldsExcluded",!entries.toString().contains("DO_NOT_STORE_RAW_PUBLIC_010"));return result;
    }
    private void collectSettingsTitles(android.view.accessibility.AccessibilityNodeInfo n,org.json.JSONArray rows,int depth)throws Exception {
        if(n==null||depth>16||rows.length()>=150)return;if(!n.refresh()||!n.isVisibleToUser())return;android.graphics.Rect b=new android.graphics.Rect();n.getBoundsInScreen(b);String id=n.getViewIdResourceName()==null?"":n.getViewIdResourceName(),cls=String.valueOf(n.getClassName());String text=n.getText()==null?"":n.getText().toString(),desc=n.getContentDescription()==null?"":n.getContentDescription().toString();
        java.util.Set<String> safe=new java.util.HashSet<>(java.util.Arrays.asList("Settings","Wi-Fi","Wi‑Fi","Bluetooth","Connected devices","Network & internet","Internet","Display","Sound","Sound & vibration"));
        if((b.top<550&&(cls.contains("Toolbar")||cls.contains("TextView")||id.contains("toolbar")||id.contains("title")))||n.isHeading())rows.put(new JSONObject().put("id",id).put("class",cls).put("heading",n.isHeading()).put("bounds",b.toShortString()).put("text",safe.contains(text)?text:"[omitted]").put("description",safe.contains(desc)?desc:"[omitted]"));
        for(int i=0;i<n.getChildCount();i++){android.view.accessibility.AccessibilityNodeInfo c=n.getChild(i);if(c!=null)try{collectSettingsTitles(c,rows,depth+1);}finally{c.recycle();}}
    }
    private JSONObject actualSettingsDiagnostics()throws Exception {
        Thread.sleep(8500);Class<?> type=Class.forName("dev.chanho.hermes.PhoneAccessibilityService");Method current=type.getDeclaredMethod("current");current.setAccessible(true);android.accessibilityservice.AccessibilityService service=(android.accessibilityservice.AccessibilityService)current.invoke(null);if(service==null)return new JSONObject().put("serviceBound",false);JSONObject result=new JSONObject();
        String[] names={"general","wifi","bluetooth","display","sound"},actions={android.provider.Settings.ACTION_SETTINGS,android.provider.Settings.ACTION_WIFI_SETTINGS,android.provider.Settings.ACTION_BLUETOOTH_SETTINGS,android.provider.Settings.ACTION_DISPLAY_SETTINGS,android.provider.Settings.ACTION_SOUND_SETTINGS};
        for(int j=0;j<actions.length;j++){String action=actions[j];runOnMainSync(()->getTargetContext().startActivity(new Intent(action).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)));Thread.sleep(1600);AtomicReference<JSONObject> entry=new AtomicReference<>();runOnMainSync(()->{try{android.view.accessibility.AccessibilityNodeInfo root=service.getRootInActiveWindow();if(root==null){entry.set(new JSONObject().put("error","no_active_root"));return;}try{root.refresh();String pkg=String.valueOf(root.getPackageName());if(!"com.android.settings".equals(pkg)){entry.set(new JSONObject().put("error","foreground_not_settings").put("package",pkg));return;}org.json.JSONArray rows=new org.json.JSONArray();collectSettingsTitles(root,rows,0);String title="";android.graphics.Rect bounds=new android.graphics.Rect();for(android.view.accessibility.AccessibilityWindowInfo w:service.getWindows())try{if(w.getId()==root.getWindowId()){title=String.valueOf(w.getTitle());w.getBoundsInScreen(bounds);}}finally{w.recycle();}entry.set(new JSONObject().put("package",pkg).put("windowId",root.getWindowId()).put("windowTitle",title).put("windowBounds",bounds.toShortString()).put("titleCandidates",rows));}finally{root.recycle();}}catch(Exception e){try{entry.set(new JSONObject().put("error",e.toString()));}catch(Exception ignored){}}});result.put(names[j],entry.get());}return result;
    }
    private void collectPublicIds(android.view.accessibility.AccessibilityNodeInfo n,org.json.JSONArray rows,int depth)throws Exception {
        if(n==null||depth>32||rows.length()>=600||!n.refresh()||!n.isVisibleToUser())return;
        String id=n.getViewIdResourceName();if(id!=null&&!id.isEmpty())rows.put(new JSONObject().put("id",id).put("class",String.valueOf(n.getClassName())).put("password",n.isPassword()));
        for(int i=0;i<n.getChildCount();i++){android.view.accessibility.AccessibilityNodeInfo c=n.getChild(i);if(c!=null)try{collectPublicIds(c,rows,depth+1);}finally{c.recycle();}}
    }
    private JSONObject actualPublicSurface()throws Exception {
        Thread.sleep(8500);if("__ANDROID_WIFI_SURFACE__".equals(script)){runOnMainSync(()->getTargetContext().startActivity(new Intent(android.provider.Settings.ACTION_WIFI_SETTINGS).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)));Thread.sleep(5000);}Class<?> type=Class.forName("dev.chanho.hermes.PhoneAccessibilityService");Method current=type.getDeclaredMethod("current");current.setAccessible(true);android.accessibilityservice.AccessibilityService service=(android.accessibilityservice.AccessibilityService)current.invoke(null);JSONObject result=new JSONObject();if(service==null)return result.put("serviceBound",false);AtomicReference<JSONObject> entry=new AtomicReference<>();
        runOnMainSync(()->{try{android.view.accessibility.AccessibilityNodeInfo root=service.getRootInActiveWindow();if(root==null){entry.set(result.put("error","no_active_root"));return;}try{root.refresh();String pkg=String.valueOf(root.getPackageName());if(!"com.android.settings".equals(pkg)&&!"com.android.systemui".equals(pkg)){entry.set(result.put("error","unexpected_foreground").put("package",pkg));return;}org.json.JSONArray ids=new org.json.JSONArray(),titles=new org.json.JSONArray();collectPublicIds(root,ids,0);if("com.android.settings".equals(pkg))collectSettingsTitles(root,titles,0);for(android.view.accessibility.AccessibilityWindowInfo w:service.getWindows())try{if(w.getId()==root.getWindowId()){android.graphics.Rect b=new android.graphics.Rect();w.getBoundsInScreen(b);result.put("windowTitle",String.valueOf(w.getTitle())).put("windowType",w.getType()).put("windowBounds",b.toShortString());}}finally{w.recycle();}entry.set(result.put("package",pkg).put("rootClass",String.valueOf(root.getClassName())).put("windowId",root.getWindowId()).put("visibleIds",ids).put("titleCandidates",titles));}finally{root.recycle();}}catch(Exception e){try{entry.set(result.put("error",e.toString()));}catch(Exception ignored){}}});return entry.get();
    }
    private JSONObject databaseThoughtProof(Activity activity,boolean readOnly)throws Exception {
      Object store=field(field(activity,"runtime"),"store");android.database.sqlite.SQLiteDatabase db=((android.database.sqlite.SQLiteOpenHelper)store).getWritableDatabase();java.io.File marker=new java.io.File(getTargetContext().getExternalFilesDir(null),"thought-test.json");JSONObject ids;
      if(readOnly){try(java.io.FileReader r=new java.io.FileReader(marker)){StringBuilder text=new StringBuilder();char[] b=new char[1024];int n;while((n=r.read(b))!=-1)text.append(b,0,n);ids=new JSONObject(text.toString());}}
      else{String sid=(String)call(store,"newSession",new Class<?>[]{String.class},"PUBLIC_THOUGHT_NATIVE_011"),other=(String)call(store,"newSession",new Class<?>[]{String.class},"PUBLIC_THOUGHT_ISOLATED_011"),run="fixture_"+java.util.UUID.randomUUID();JSONObject event=new JSONObject().put("provider","mimo").put("source","mimo.reasoning_content").put("session",sid).put("runId",run).put("round",1).put("text","PUBLIC_THOUGHT_FIRST_011").put("timestamp",1000).put("token","DROP_FAKE_PRIVATE_FIELDS_011").put("reasoning_content","DROP_FAKE_PRIVATE_FIELDS_011").put("imageDataURL","DROP_FAKE_PRIVATE_FIELDS_011").put("output","DROP_FAKE_PRIVATE_FIELDS_011");call(store,"recordProviderThought",new Class<?>[]{JSONObject.class},event);event.put("timestamp",2000).put("text","PUBLIC_THOUGHT_FIRST_011 PUBLIC_THOUGHT_SECOND_011");call(store,"recordProviderThought",new Class<?>[]{JSONObject.class},event);event.put("session",other).put("runId",run+"_other").put("text","PUBLIC_OTHER_011");call(store,"recordProviderThought",new Class<?>[]{JSONObject.class},event);ids=new JSONObject().put("session",sid).put("otherSession",other);try(java.io.FileWriter w=new java.io.FileWriter(marker)){w.write(ids.toString());}}
      JSONArray rows=(JSONArray)call(store,"providerThoughts",new Class<?>[]{String.class},ids.getString("session")),otherRows=(JSONArray)call(store,"providerThoughts",new Class<?>[]{String.class},ids.getString("otherSession"));JSONObject result=databaseTimeline(activity,true).put("thoughtIds",ids).put("publicThoughts",rows).put("otherPublicThoughts",otherRows).put("singleCumulativeRow",rows.length()==1).put("firstTimestampPreserved",rows.length()==1&&rows.getJSONObject(0).getLong("firstTimestamp")==1000).put("sessionIsolated",otherRows.length()==1&&!rows.getJSONObject(0).getString("text").equals(otherRows.getJSONObject(0).getString("text"))).put("unapprovedRawFieldsExcluded",!rows.toString().contains("DROP_FAKE_PRIVATE_FIELDS_011"));JSONArray columns=new JSONArray();try(android.database.Cursor c=db.rawQuery("PRAGMA table_info(provider_thoughts)",null)){while(c.moveToNext())columns.put(c.getString(1));}return result.put("providerThoughtColumns",columns);
    }
    private JSONObject isolatedTimelineMigrations()throws Exception {
      JSONArray cases=new JSONArray();
      for(int oldVersion:new int[]{1,2,3}){
        final String suffix="timeline_v"+oldVersion+"_"+java.util.UUID.randomUUID();final java.io.File file=getTargetContext().getDatabasePath(suffix+".db");file.getParentFile().mkdirs();
        android.database.sqlite.SQLiteDatabase legacy=android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(file,null);
        legacy.execSQL("CREATE TABLE sessions(id TEXT PRIMARY KEY,title TEXT NOT NULL,created INTEGER NOT NULL)");legacy.execSQL("CREATE TABLE messages(id INTEGER PRIMARY KEY AUTOINCREMENT,sid TEXT NOT NULL,role TEXT NOT NULL,body TEXT NOT NULL,created INTEGER NOT NULL)");legacy.execSQL("CREATE TABLE transcripts(sid TEXT PRIMARY KEY,body TEXT NOT NULL)");legacy.execSQL("CREATE TABLE audit(id INTEGER PRIMARY KEY AUTOINCREMENT,tool TEXT NOT NULL,status TEXT NOT NULL,detail TEXT NOT NULL,created INTEGER NOT NULL)");
        legacy.execSQL("INSERT INTO sessions VALUES('public_session','PUBLIC_LEGACY',100)");legacy.execSQL("INSERT INTO messages(sid,role,body,created) VALUES('public_session','user','PUBLIC_LEGACY_USER',100)");legacy.execSQL("INSERT INTO messages(sid,role,body,created) VALUES('public_session','assistant','PUBLIC_LEGACY_ANSWER',400)");legacy.execSQL("INSERT INTO transcripts VALUES('public_session','PUBLIC_LEGACY_TRANSCRIPT')");legacy.execSQL("INSERT INTO audit(tool,status,detail,created) VALUES('memory','completed','PUBLIC_LEGACY_AUDIT',200)");
        if(oldVersion>=2){legacy.execSQL("CREATE TABLE activities(id INTEGER PRIMARY KEY AUTOINCREMENT,sid TEXT NOT NULL,run_id TEXT NOT NULL,call_id TEXT NOT NULL,kind TEXT NOT NULL,body TEXT NOT NULL,created INTEGER NOT NULL,UNIQUE(run_id,call_id,kind))");legacy.execSQL("INSERT INTO activities(sid,run_id,call_id,kind,body,created) VALUES('public_session','legacy_run','legacy_tool','tool','{\"session\":\"public_session\",\"runId\":\"legacy_run\",\"kind\":\"tool\",\"toolCallId\":\"legacy_tool\",\"summary\":\"PUBLIC_LEGACY_TOOL\"}',250)");}
        if(oldVersion>=3){legacy.execSQL("CREATE TABLE provider_thoughts(id INTEGER PRIMARY KEY AUTOINCREMENT,sid TEXT NOT NULL,run_id TEXT NOT NULL,round INTEGER NOT NULL,body TEXT NOT NULL,created INTEGER NOT NULL,UNIQUE(run_id,round))");legacy.execSQL("INSERT INTO provider_thoughts(sid,run_id,round,body,created) VALUES('public_session','legacy_run',1,'{\"session\":\"public_session\",\"runId\":\"legacy_run\",\"round\":1,\"provider\":\"mimo\",\"source\":\"mimo.reasoning_content\",\"text\":\"PUBLIC_LEGACY_THOUGHT\"}',1)");}
        legacy.setVersion(oldVersion);legacy.close();
        Context isolated=new ContextWrapper(getTargetContext()){
          @Override public java.io.File getDatabasePath(String name){return file;}
          @Override public android.content.SharedPreferences getSharedPreferences(String name,int mode){return super.getSharedPreferences(suffix+"_"+name,mode);}
          @Override public android.database.sqlite.SQLiteDatabase openOrCreateDatabase(String name,int mode,android.database.sqlite.SQLiteDatabase.CursorFactory factory){return android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(file,factory);}
          @Override public android.database.sqlite.SQLiteDatabase openOrCreateDatabase(String name,int mode,android.database.sqlite.SQLiteDatabase.CursorFactory factory,android.database.DatabaseErrorHandler handler){return android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(file.getAbsolutePath(),factory,handler);}
        };
        Class<?> type=Class.forName("dev.chanho.hermes.Store");Constructor<?> constructor=type.getDeclaredConstructor(Context.class);constructor.setAccessible(true);Object store=constructor.newInstance(isolated);
        call(store,"saveConfig",new Class<?>[]{JSONObject.class},new JSONObject().put("providerId","custom").put("endpoint","http://127.0.0.1:8894").put("allowLan",true).put("model","public-legacy-migration").put("token","PUBLIC_FAKE_MIGRATION_CREDENTIAL"));call(store,"put",new Class<?>[]{String.class,String.class},"memory","PUBLIC_LEGACY_MEMORY");
        android.database.sqlite.SQLiteDatabase db=((android.database.sqlite.SQLiteOpenHelper)store).getWritableDatabase();JSONArray messages=(JSONArray)call(store,"messages",new Class<?>[]{String.class},"public_session"),activities=(JSONArray)call(store,"activities",new Class<?>[]{String.class},"public_session"),thoughts=(JSONArray)call(store,"providerThoughts",new Class<?>[]{String.class},"public_session");
        JSONObject result=new JSONObject().put("from",oldVersion).put("to",db.getVersion()).put("messages",messages).put("activities",activities).put("thoughts",thoughts).put("credentialPreserved","PUBLIC_FAKE_MIGRATION_CREDENTIAL".equals(call(store,"secret",new Class<?>[]{String.class},"token"))).put("memoryPreserved","PUBLIC_LEGACY_MEMORY".equals(call(store,"get",new Class<?>[]{String.class,String.class},"memory",""))).put("messageCountPreserved",messages.length()==2).put("activityCountPreserved",activities.length()==(oldVersion>=2?1:0)).put("thoughtCountPreserved",thoughts.length()==(oldVersion>=3?1:0));
        boolean positive=true;java.util.HashSet<Long> orders=new java.util.HashSet<>();for(JSONArray group:new JSONArray[]{messages,activities,thoughts})for(int i=0;i<group.length();i++){long order=group.getJSONObject(i).optLong("timelineOrder",0);positive&=order>0&&orders.add(order);}result.put("allOrdersPositiveUnique",positive);if(oldVersion==3)result.put("clockSkewThoughtClampedAfterUser",thoughts.getJSONObject(0).getLong("timelineOrder")>messages.getJSONObject(0).getLong("timelineOrder"));
        try(android.database.Cursor c=db.rawQuery("SELECT body FROM transcripts WHERE sid='public_session'",null)){result.put("transcriptPreserved",c.moveToFirst()&&c.getString(0).equals("PUBLIC_LEGACY_TRANSCRIPT"));}try(android.database.Cursor c=db.rawQuery("SELECT detail FROM audit WHERE tool='memory'",null)){result.put("auditPreserved",c.moveToFirst()&&c.getString(0).equals("PUBLIC_LEGACY_AUDIT"));}
        ((android.database.sqlite.SQLiteOpenHelper)store).close();cases.put(result);
      }return new JSONObject().put("cases",cases);
    }
    private JSONObject compactFixture(Activity activity,boolean verify)throws Exception {
      Object store=field(field(activity,"runtime"),"store");java.io.File marker=new java.io.File(getTargetContext().getExternalFilesDir(null),"compact-test.json");JSONObject data;
      if(!verify){String sid=(String)call(store,"newSession",new Class<?>[]{String.class},"PUBLIC_COMPACT_NATIVE_012");JSONArray transcript=new JSONArray().put(new JSONObject().put("role","system").put("content","Public compact fixture system"));StringBuilder padding=new StringBuilder();for(int j=0;j<350;j++)padding.append("public quoted fixture ");for(int i=0;i<8;i++){String user="PUBLIC_OLD_USER_"+i+" "+padding,answer="PUBLIC_OLD_ANSWER_"+i+" "+padding;transcript.put(new JSONObject().put("role","user").put("content",user)).put(new JSONObject().put("role","assistant").put("content",answer).put("reasoning_content","PUBLIC_OLD_REASONING_NOT_SUMMARIZED"));call(store,"message",new Class<?>[]{String.class,String.class,String.class},sid,"user",user);call(store,"message",new Class<?>[]{String.class,String.class,String.class},sid,"assistant",answer);}call(store,"transcript",new Class<?>[]{String.class,JSONArray.class},sid,transcript);java.security.MessageDigest md=java.security.MessageDigest.getInstance("SHA-256");data=new JSONObject().put("session",sid).put("originalSha",android.util.Base64.encodeToString(md.digest(transcript.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8)),android.util.Base64.NO_WRAP)).put("originalRows",transcript.length());try(java.io.FileWriter writer=new java.io.FileWriter(marker)){writer.write(data.toString());}return data;}
      try(java.io.FileReader r=new java.io.FileReader(marker)){StringBuilder text=new StringBuilder();char[] b=new char[1024];int n;while((n=r.read(b))!=-1)text.append(b,0,n);data=new JSONObject(text.toString());}JSONArray transcript=(JSONArray)call(store,"transcript",new Class<?>[]{String.class},data.getString("session"));String sha=android.util.Base64.encodeToString(java.security.MessageDigest.getInstance("SHA-256").digest(transcript.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8)),android.util.Base64.NO_WRAP);String checkpoint=(String)call(store,"get",new Class<?>[]{String.class,String.class},"compact:"+data.getString("session"),"");return data.put("originalTranscriptUnchanged",data.getString("originalSha").equals(sha)).put("currentRows",transcript.length()).put("publicReasoningOriginalRetained",transcript.toString().contains("PUBLIC_OLD_REASONING_NOT_SUMMARIZED")).put("checkpoint",checkpoint.isEmpty()?new JSONObject():new JSONObject(checkpoint));
    }
    private JSONObject actualDiagnosticsProof(Activity activity)throws Exception {
      Class<?> type=Class.forName("dev.chanho.hermes.Diagnostics");Method record=type.getDeclaredMethod("record",Context.class,String.class,Throwable.class);record.invoke(null,activity,"runtime",new IllegalStateException("PUBLIC_DIAG_FAKE_TOKEN=DROP_PUBLIC_FAKE_SECRET_012 pixels=DROP_PUBLIC_FAKE_PIXELS_012"));android.net.Uri uri=android.net.Uri.parse("content://dev.chanho.hermes.diagnostics/events");JSONObject result=new JSONObject().put("uid",android.os.Process.myUid());ByteArrayOutputStream bytes=new ByteArrayOutputStream();try(java.io.InputStream in=activity.getContentResolver().openInputStream(uri)){byte[] b=new byte[4096];int n;while((n=in.read(b))!=-1)bytes.write(b,0,n);}String rows=bytes.toString("UTF-8");result.put("actualSameUidRead",!rows.isEmpty()).put("rawFailureMessageExcluded",!rows.contains("DROP_PUBLIC_FAKE_SECRET_012")&&!rows.contains("DROP_PUBLIC_FAKE_PIXELS_012")).put("report",rows);JSONArray denied=new JSONArray();for(String[] spec:new String[][]{{"content://dev.chanho.hermes.diagnostics/events","rw"},{"content://dev.chanho.hermes.diagnostics/other","r"},{"content://dev.chanho.hermes.diagnostics/events?path=/data","r"}}){JSONObject row=new JSONObject().put("uri",spec[0]).put("mode",spec[1]);try(android.os.ParcelFileDescriptor ignored=activity.getContentResolver().openFileDescriptor(android.net.Uri.parse(spec[0]),spec[1])){row.put("denied",false);}catch(Exception e){row.put("denied",true).put("exceptionClass",e.getClass().getSimpleName());}denied.put(row);}result.put("invalidPathAndWriteDenied",denied);
      java.io.File file=new java.io.File(activity.getFilesDir(),"diagnostics/events.jsonl");byte[] backup;try(java.io.InputStream in=new java.io.FileInputStream(file)){ByteArrayOutputStream original=new ByteArrayOutputStream();byte[] b=new byte[4096];int n;while((n=in.read(b))!=-1)original.write(b,0,n);backup=original.toByteArray();}
      try{try(java.io.OutputStream out=new java.io.FileOutputStream(file)){out.write("{corrupt public diagnostic fixture".getBytes(java.nio.charset.StandardCharsets.UTF_8));}try(java.io.InputStream ignored=activity.getContentResolver().openInputStream(uri)){result.put("corruptReadFailsClosed",false);}catch(Exception e){result.put("corruptReadFailsClosed",true).put("corruptReadErrorClass",e.getClass().getSimpleName());}}
      finally{try(java.io.OutputStream out=new java.io.FileOutputStream(file)){out.write(backup);}result.put("originalDiagnosticBytesRestored",true);}return result;
    }
    @Override public void onStart(){
        Bundle output=new Bundle();
        try{
            Intent intent=new Intent();intent.setClassName("dev.chanho.hermes","dev.chanho.hermes.MainActivity");intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            Activity activity=startActivitySync(intent);Thread.sleep(1800);
            WebView found=find(activity.getWindow().getDecorView());if(found==null)throw new IllegalStateException("No actual WebView");
            if(script.startsWith("__MIMO_MULTIROUND_FIXTURE__\n")){Object store=field(field(activity,"runtime"),"store");call(store,"saveConfig",new Class<?>[]{JSONObject.class},new JSONObject().put("providerId","custom").put("endpoint","http://127.0.0.1:8895").put("allowLan",true).put("model","public-mimo-three-round-fixture").put("token","PUBLIC_LOCAL_FIXTURE_KEY_ONLY").put("enabledPlugins",new JSONArray().put("agent")).put("approvalMode","auto").put("deviceScope","all"));call(store,"put",new Class<?>[]{String.class,String.class},"provider_id","xiaomi");script=script.substring("__MIMO_MULTIROUND_FIXTURE__\n".length());}
            if(script.startsWith("__MIMO_LOCAL_FIXTURE__\n")){Object store=field(field(activity,"runtime"),"store");call(store,"saveConfig",new Class<?>[]{JSONObject.class},new JSONObject().put("providerId","custom").put("endpoint","http://127.0.0.1:8894").put("allowLan",true).put("model","public-mimo-fixture").put("token","PUBLIC_LOCAL_FIXTURE_KEY_ONLY").put("enabledPlugins",new JSONArray().put("agent")).put("approvalMode","auto").put("deviceScope","all"));call(store,"put",new Class<?>[]{String.class,String.class},"provider_id","xiaomi");script=script.substring("__MIMO_LOCAL_FIXTURE__\n".length());}
            JSONObject lifecycleResult=null;
            if("__ANDROID_DIAGNOSTICS_PROOF__".equals(script)){output.putString("probe",actualDiagnosticsProof(activity).toString());finish(Activity.RESULT_OK,output);return;}
            if("__ANDROID_COMPACT_SEED__".equals(script)||"__ANDROID_COMPACT_VERIFY__".equals(script)){output.putString("probe",compactFixture(activity,"__ANDROID_COMPACT_VERIFY__".equals(script)).toString());finish(Activity.RESULT_OK,output);return;}
            if("__ANDROID_DB4_ISOLATED_MIGRATIONS__".equals(script)){output.putString("probe",isolatedTimelineMigrations().toString());finish(Activity.RESULT_OK,output);return;}
            if("__ANDROID_DB3_PROOF__".equals(script)||"__ANDROID_DB3_REOPEN__".equals(script)){output.putString("probe",databaseThoughtProof(activity,"__ANDROID_DB3_REOPEN__".equals(script)).toString());finish(Activity.RESULT_OK,output);return;}
            if("__ANDROID_PUBLIC_SURFACE__".equals(script)||"__ANDROID_WIFI_SURFACE__".equals(script)){output.putString("probe",actualPublicSurface().toString());finish(Activity.RESULT_OK,output);return;}
            if("__ANDROID_SETTINGS_HEADINGS__".equals(script)){output.putString("probe",actualSettingsDiagnostics().toString());finish(Activity.RESULT_OK,output);return;}
            if("__ANDROID_DB_V2_CREATE__".equals(script)||"__ANDROID_DB_V2_REOPEN__".equals(script)){output.putString("probe",databaseTimeline(activity,"__ANDROID_DB_V2_REOPEN__".equals(script)).toString());finish(Activity.RESULT_OK,output);return;}
            if("__ANDROID_DB_V1_BASELINE__".equals(script)){output.putString("probe",databaseBaseline(activity).toString());finish(Activity.RESULT_OK,output);return;}
            if("__ANDROID_WINDOW_DIAGNOSTICS__".equals(script)){output.putString("probe",actualWindowDiagnostics().toString());finish(Activity.RESULT_OK,output);return;}
            if("__ANDROID_LIFECYCLE__".equals(script)){lifecycleResult=lifecycle(activity,found);script="return {version:(await native('boot')).version,bridgePresent:!!window.NativeBridge,appLoaded:!!document.getElementById('app')};";found=find(activity.getWindow().getDecorView());}
            if("__ANDROID_NEWCHAT__".equals(script)){lifecycleResult=newChatIme(activity,found);script="return {version:(await native('boot')).version,newChatInputUnfocused:document.activeElement!==document.getElementById('messageInput')};";}
            if("__ANDROID_QUEUE_CANCEL__".equals(script)){lifecycleResult=queuedCancel(activity);script="return {version:(await native('boot')).version};";}
            final WebView web=found;
            runOnMainSync(()->{web.addJavascriptInterface(new ProbeBridge(),"PocketProbe");web.reload();});Thread.sleep(1800);
            runOnMainSync(()->{web.evaluateJavascript("(async()=>{try{const result=await(async()=>{"+script+"})();PocketProbe.report(JSON.stringify({ok:true,result}));}catch(e){PocketProbe.report(JSON.stringify({ok:false,error:e.message}));}})()",null);});
            String reply=null;if(script.contains("PASSWORD")||script.contains("actual_accessibility_service_bound")){for(int i=0;i<750&&reply==null;i++){try{dumpAutomation();}catch(Exception ignored){}reply=replies.poll(200,TimeUnit.MILLISECONDS);}}else reply=replies.poll(150,TimeUnit.SECONDS);if(reply==null)throw new IllegalStateException("No JavaScript bridge reply within150s");if(lifecycleResult!=null){JSONObject r=new JSONObject(reply);r.put("lifecycle",lifecycleResult);reply=r.toString();}output.putString("probe",reply);Thread.sleep(1200); // Allow production SharedPreferences.apply() disk writes before instrumentation ends its process.
            runOnMainSync(()->web.removeJavascriptInterface("PocketProbe"));finish(Activity.RESULT_OK,output);
        }catch(Exception e){output.putString("probe","{\"ok\":false,\"error\":\""+e.toString().replace("\"","'")+"\"}");finish(Activity.RESULT_CANCELED,output);}
    }
}
