const checks={},results={};const assert=(ok,name)=>{checks[name]=!!ok;if(!ok)throw Error(name);};async function run(name,args={}){let r;try{r=await native('runTool',{name,arguments:args});}catch(e){r={error:e.message};}for(let i=0;i<100&&(await native('boot')).busy;i++)await new Promise(r=>setTimeout(r,30));return r;}
try{
await native('setCapabilities',{enabledPlugins:['device','screen','root','agent','web','files','terminal'],deviceScope:'all',approvalMode:'auto',floatingEnabled:true});const boot=await native('boot');results.inventory=boot.availableTools;assert(boot.availableTools.names.includes('terminal')&&boot.availableTools.names.includes('process_manage')&&boot.availableTools.count===boot.availableTools.names.length,'native_terminal_inventory_authority');results.skills=await native('skillsList');results.skill=await run('skill_view',{name:'android-terminal'});assert(JSON.stringify(results.skill).includes('android-terminal'),'actual_builtin_terminal_skill_seed');
results.identity=await run('terminal',{command:"printf 'APP_PUBLIC_009\\n'; id -u; pwd"});assert(results.identity.exit_code===0&&results.identity.output.includes('APP_PUBLIC_009')&&!results.identity.output.includes('\n2000\n')&&!results.identity.output.includes('\n0\n'),'actual_app_uid_shell');
results.environmentSetup=await run('terminal',{command:'mkdir -p persisted; cd persisted; export HERMES_TEST_VALUE=ENV_PUBLIC_009; pwd'});results.environmentRead=await run('terminal',{command:'pwd; printf "%s\\n" "$HERMES_TEST_VALUE"'});assert(results.environmentRead.exit_code===0&&results.environmentRead.output.includes('/persisted')&&results.environmentRead.output.includes('ENV_PUBLIC_009'),'real_cwd_and_export_persist');
results.error=await run('terminal',{command:"printf 'EXPECTED_ERROR_PUBLIC_009\\n' >&2; false"});assert(results.error.exit_code===1&&results.error.output.includes('EXPECTED_ERROR_PUBLIC_009'),'actual_stderr_and_nonzero_exit');results.timeout=await run('terminal',{command:'sleep 4',timeout:1});assert(results.timeout.status==='timeout'&&!results.timeout.running,'actual_timeout_kills_process');
results.background=await run('terminal',{command:'read line; printf "STDIN_PUBLIC:%s\\n" "$line"; sleep 10',background:true,timeout:30});assert(results.background.running&&results.background.session_id,'actual_background_session');const sid=results.background.session_id;results.idleBoot=await native('boot');assert(!results.idleBoot.busy&&results.idleBoot.terminal.running,'background_owned_after_tool_return');results.submit=await run('process_manage',{action:'submit',session_id:sid,data:'NATIVE_STDIN_009'});await new Promise(r=>setTimeout(r,500));results.poll=await run('process_manage',{action:'poll',session_id:sid});assert(results.poll.output.includes('STDIN_PUBLIC:NATIVE_STDIN_009'),'actual_stdin_and_incremental_poll');results.log=await run('process_manage',{action:'log',session_id:sid});assert(results.log.output.includes('NATIVE_STDIN_009'),'retained_real_process_log');results.kill=await run('process_manage',{action:'kill',session_id:sid});assert(!results.kill.running&&results.kill.status==='killed','actual_owned_process_kill');
results.pty=await run('terminal',{command:'id',pty:true});assert(results.pty.error?.includes('PTY'),'unsupported_pty_refused');await native('setCapabilities',{enabledPlugins:['device','screen','agent']});results.disabled=await run('terminal',{command:'printf DISABLED_MUST_NOT_RUN'});assert(results.disabled.error,'disabled_terminal_refused');await native('setCapabilities',{enabledPlugins:['device','screen','root','agent','web','files','terminal']});return {version:(await native('boot')).version,checks,results};
}catch(e){return {checks,results,failure:e.message};}
