__MIMO_LOCAL_FIXTURE__
const checks={},results={};const assert=(ok,id)=>{checks[id]=!!ok;if(!ok)throw Error(id);};try{

startNewChat();await native('startChat',{text:'Public local streaming fixture only'});let first=null;
for(let i=0;i<100;i++){const thought=document.querySelector('.provider-thought');if(thought){first={thought:thought.innerText,body:thought.querySelector('.provider-thought-body')?.textContent,collapsed:!thought.querySelector('details')?.open,answerText:state.live,busy:state.busy,phase:state.modelProgress?.phase,timer:modelProgressElapsed()};break;}await new Promise(r=>setTimeout(r,40));}
results.first=first;const label=document.getElementById('chatModelProgress');if(label){const rect=label.getBoundingClientRect(),parent=label.closest('.message-label');results.visibleElapsed={text:label.innerText,width:rect.width,height:rect.height,display:getComputedStyle(label).display,parentDisplay:parent?getComputedStyle(parent).display:'missing'};}assert(results.visibleElapsed&&results.visibleElapsed.width>0&&results.visibleElapsed.height>0&&results.visibleElapsed.parentDisplay!=='none','actual_elapsed_label_visible');assert(first&&first.body.includes('PUBLIC_FIXTURE_THOUGHT_FIRST')&&first.busy&&!first.answerText,'actual_SSE_public_thought_visible_before_answer');assert(first.collapsed,'actual_public_card_collapsed_default');await new Promise(r=>setTimeout(r,400));results.liveElapsed=modelProgressElapsed();assert(results.liveElapsed>first.timer+250,'actual_live_elapsed_advances');
for(let i=0;i<150&&(await native('boot')).busy;i++)await new Promise(r=>setTimeout(r,50));const boot=await native('boot');results.publicSession=boot.session;results.publicThoughts=await native('providerThoughts',{session:boot.session});results.publicMessages=await native('messages',{session:boot.session});results.finalPhase=state.modelProgress?.phase;results.elapsedEnd=modelProgressElapsed();await new Promise(r=>setTimeout(r,350));assert(modelProgressElapsed()===results.elapsedEnd&&modelProgressTimer===null,'actual_timer_stops_after_completion');assert(results.publicThoughts.length===1&&results.publicThoughts[0].text==='PUBLIC_FIXTURE_THOUGHT_FIRST PUBLIC_FIXTURE_THOUGHT_SECOND','native_public_thought_cumulative_single_persisted_row');assert(!results.publicMessages.some(m=>(m.content||'').includes('PUBLIC_FIXTURE_THOUGHT_FIRST')),'public_thought_separate_from_answer_messages');
await native('saveSettings',{providerId:'custom',mode:'direct',endpoint:'http://127.0.0.1:8894',allowLan:true,model:'non-mimo-fixture',token:'PUBLIC_LOCAL_FIXTURE_KEY_ONLY'});startNewChat();await native('startChat',{text:'Non MiMo local privacy fixture only'});for(let i=0;i<150&&(await native('boot')).busy;i++)await new Promise(r=>setTimeout(r,50));const ordinary=await native('boot');results.ordinarySession=ordinary.session;results.ordinaryThoughts=await native('providerThoughts',{session:ordinary.session});results.ordinaryConversation=document.getElementById('conversation').innerText;assert(results.ordinaryThoughts.length===0&&!results.ordinaryConversation.includes('UNSUPPORTED_FIXTURE'),'actual_nonMiMo_reasoning_not_in_public_store_or_UI');assert(results.publicSession!==results.ordinarySession,'actual_distinct_native_sessions');await openSession((await native('sessions')).find(s=>s.id===results.publicSession));await new Promise(r=>setTimeout(r,200));assert(document.querySelectorAll('.provider-thought').length===1&&document.querySelector('.provider-thought-body').textContent.includes('PUBLIC_FIXTURE_THOUGHT_SECOND'),'actual_persisted_public_card_reopens');return {version:(await native('boot')).version,checks,results};
}catch(e){return {checks,results,failure:e.message};}
