#!/usr/bin/env python3
"""Single-source Android release numbering: v0.01, v0.02, …, v1.00."""
import argparse
from dataclasses import dataclass
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
ANDROID_NS = "http://schemas.android.com/apk/res/android"
MAX_CODE = 2_100_000_000


@dataclass(frozen=True)
class Version:
    major: int
    minor: int
    channel: str

    def __post_init__(self):
        if type(self.major) is not int or self.major < 0:
            raise ValueError("major must be a nonnegative integer")
        if type(self.minor) is not int or not 0 <= self.minor <= 99:
            raise ValueError("minor must be an integer from 0 through 99")
        if self.channel not in ("beta", "stable"):
            raise ValueError("channel must be beta or stable")
        if not 1 <= self.version_code <= MAX_CODE:
            raise ValueError("v0.00 is reserved; release versionCode must be 1..2100000000")

    @property
    def version_name(self):
        return f"{self.major}.{self.minor:02d}"

    @property
    def display_version(self):
        return "v" + self.version_name

    @property
    def version_code(self):
        return self.major * 100 + self.minor

    @property
    def apk_name(self):
        return f"hermes-pocket-v{self.version_name}.apk"

    def next(self, major=False, channel=None):
        if major:
            return Version(self.major + 1, 0, channel or self.channel)
        code = self.version_code + 1
        return Version(code // 100, code % 100, channel or self.channel)

    def as_dict(self):
        return {"major": self.major, "minor": self.minor, "channel": self.channel}


def load_version(root=ROOT):
    data = json.loads((Path(root) / "version.json").read_text(encoding="utf-8"))
    if set(data) != {"major", "minor", "channel"}:
        raise ValueError("version.json must contain only major, minor, channel")
    return Version(**data)


def java_source(version):
    return f'''// Generated by scripts/versioning.py from version.json. Do not edit.
package dev.chanho.hermes;

public final class BuildConfig {{
    private BuildConfig() {{}}
    public static final int VERSION_CODE = {version.version_code};
    public static final String VERSION_NAME = "{version.version_name}";
    public static final String DISPLAY_VERSION = "{version.display_version}";
    public static final String RELEASE_CHANNEL = "{version.channel}";
}}
'''


def generated_paths(root):
    root = Path(root)
    return (root / "app/src/main/java/dev/chanho/hermes/BuildConfig.java",
            root / "app/src/main/AndroidManifest.xml")


def sync_version(root=ROOT):
    version = load_version(root)
    java, manifest = generated_paths(root)
    java.parent.mkdir(parents=True, exist_ok=True)
    java.write_text(java_source(version), encoding="utf-8")
    source = manifest.read_text(encoding="utf-8")
    source = re.sub(r' android:version(?:Code|Name)="[^"]*"', "", source)
    source = source.replace('<manifest ', '<manifest android:versionCode="' + str(version.version_code)
                            + '" android:versionName="' + version.version_name + '" ', 1)
    manifest.write_text(source, encoding="utf-8")
    return version


def check_version(root=ROOT):
    import xml.etree.ElementTree as ET
    version = load_version(root)
    java, manifest = generated_paths(root)
    if not java.is_file() or java.read_text(encoding="utf-8") != java_source(version):
        raise ValueError("BuildConfig.java is stale; run scripts/versioning.py sync")
    attrs = ET.parse(manifest).getroot().attrib
    if (attrs.get("{" + ANDROID_NS + "}versionCode") != str(version.version_code)
            or attrs.get("{" + ANDROID_NS + "}versionName") != version.version_name):
        raise ValueError("Manifest version is stale; run scripts/versioning.py sync")
    return version


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=("show", "check", "sync", "bump"))
    parser.add_argument("--major", action="store_true", help="bump to the next major .00")
    parser.add_argument("--channel", choices=("beta", "stable"))
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    if args.action != "bump" and (args.major or args.channel or args.dry_run):
        parser.error("--major, --channel and --dry-run apply only to bump")
    version = load_version()
    if args.action == "bump":
        version = version.next(major=args.major, channel=args.channel)
        if not args.dry_run:
            (ROOT / "version.json").write_text(json.dumps(version.as_dict(), indent=2) + "\n", encoding="utf-8")
            sync_version()
    elif args.action == "sync":
        sync_version()
    elif args.action == "check":
        check_version()
    print(json.dumps({**version.as_dict(), "versionName": version.version_name,
                      "versionCode": version.version_code, "displayVersion": version.display_version,
                      "apk": version.apk_name}, ensure_ascii=False))


if __name__ == "__main__":
    main()
